Repository wecode-bootcamp-korea/westagram-backend, pull requests merged in 2020-11, with the labels that each got.

#57 [정다솜] [mission4] 게시글 등록
  students/12th/dasomjung/intro.txt
  students/12th/dasomjung/project_westagram/manage.py
  students/12th/dasomjung/project_westagram/posting/__init__.py
  students/12th/dasomjung/project_westagram/posting/admin.py
  students/12th/dasomjung/project_westagram/posting/apps.py
  students/12th/dasomjung/project_westagram/posting/migrations/0001_initial.py
  students/12th/dasomjung/project_westagram/posting/migrations/0002_auto_20200904_1049.py
  students/12th/dasomjung/project_westagram/posting/migrations/0003_auto_20200904_1129.py
  students/12th/dasomjung/project_westagram/posting/migrations/0004_auto_20200906_0752.py
  students/12th/dasomjung/project_westagram/posting/migrations/0005_auto_20200906_0858.py
  students/12th/dasomjung/project_westagram/posting/migrations/__init__.py
  students/12th/dasomjung/project_westagram/posting/models.py
  students/12th/dasomjung/project_westagram/posting/tests.py
  students/12th/dasomjung/project_westagram/posting/urls.py
  students/12th/dasomjung/project_westagram/posting/views.py
  students/12th/dasomjung/project_westagram/project_westagram/__init__.py
  students/12th/dasomjung/project_westagram/project_westagram/asgi.py
  students/12th/dasomjung/project_westagram/project_westagram/settings.py
  students/12th/dasomjung/project_westagram/project_westagram/urls.py
  students/12th/dasomjung/project_westagram/project_westagram/wsgi.py
  students/12th/dasomjung/project_westagram/user/__init__.py
  students/12th/dasomjung/project_westagram/user/admin.py
  students/12th/dasomjung/project_westagram/user/apps.py
  students/12th/dasomjung/project_westagram/user/migrations/0001_initial.py
  students/12th/dasomjung/project_westagram/user/migrations/0002_auto_20200901_0754.py
  students/12th/dasomjung/project_westagram/user/migrations/0003_remove_users_user_name.py
  students/12th/dasomjung/project_westagram/user/migrations/0004_auto_20200902_1050.py
  students/12th/dasomjung/project_westagram/user/migrations/__init__.py
  students/12th/dasomjung/project_westagram/user/models.py
  students/12th/dasomjung/project_westagram/user/tests.py
  students/12th/dasomjung/project_westagram/user/urls.py
  students/12th/dasomjung/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#56 [강경훈] Mission 5: 게시물에 댓글(대댓글) 등록
  students/12th/kyunghun/intro.txt
  students/12th/kyunghun/project_westagram/manage.py
  students/12th/kyunghun/project_westagram/posting/__init__.py
  students/12th/kyunghun/project_westagram/posting/admin.py
  students/12th/kyunghun/project_westagram/posting/apps.py
  students/12th/kyunghun/project_westagram/posting/migrations/0001_initial.py
  students/12th/kyunghun/project_westagram/posting/migrations/0002_auto_20200906_1548.py
  students/12th/kyunghun/project_westagram/posting/migrations/0003_auto_20200909_0251.py
  students/12th/kyunghun/project_westagram/posting/migrations/0004_auto_20200912_2114.py
  students/12th/kyunghun/project_westagram/posting/migrations/__init__.py
  students/12th/kyunghun/project_westagram/posting/models.py
  students/12th/kyunghun/project_westagram/posting/tests.py
  students/12th/kyunghun/project_westagram/posting/urls.py
  students/12th/kyunghun/project_westagram/posting/utils.py
  students/12th/kyunghun/project_westagram/posting/views.py
  students/12th/kyunghun/project_westagram/user/__init__.py
  students/12th/kyunghun/project_westagram/user/admin.py
  students/12th/kyunghun/project_westagram/user/apps.py
  students/12th/kyunghun/project_westagram/user/migrations/0001_initial.py
  students/12th/kyunghun/project_westagram/user/migrations/0002_users_phon_number.py
  students/12th/kyunghun/project_westagram/user/migrations/0003_auto_20200904_2307.py
  students/12th/kyunghun/project_westagram/user/migrations/0004_auto_20200906_1547.py
  students/12th/kyunghun/project_westagram/user/migrations/0005_auto_20200909_0251.py
  students/12th/kyunghun/project_westagram/user/migrations/0006_auto_20200910_1434.py
  students/12th/kyunghun/project_westagram/user/migrations/0007_auto_20200910_1537.py
  students/12th/kyunghun/project_westagram/user/migrations/__init__.py
  students/12th/kyunghun/project_westagram/user/models.py
  students/12th/kyunghun/project_westagram/user/tests.py
  students/12th/kyunghun/project_westagram/user/urls.py
  students/12th/kyunghun/project_westagram/user/views.py
  students/12th/kyunghun/project_westagram/westagram/__init__.py
  students/12th/kyunghun/project_westagram/westagram/asgi.py
  students/12th/kyunghun/project_westagram/westagram/settings.py
  students/12th/kyunghun/project_westagram/westagram/urls.py
  students/12th/kyunghun/project_westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#55 [문성호] Mission 3 : 로그인 엔드포인트
  students/12th/sunghomoon/intro.txt
  students/12th/sunghomoon/project_westagram/Posting/__init__.py
  students/12th/sunghomoon/project_westagram/Posting/admin.py
  students/12th/sunghomoon/project_westagram/Posting/apps.py
  students/12th/sunghomoon/project_westagram/Posting/migrations/0001_initial.py
  students/12th/sunghomoon/project_westagram/Posting/migrations/0002_remove_post_pub_time.py
  students/12th/sunghomoon/project_westagram/Posting/migrations/0003_post_pubtime.py
  students/12th/sunghomoon/project_westagram/Posting/migrations/__init__.py
  students/12th/sunghomoon/project_westagram/Posting/models.py
  students/12th/sunghomoon/project_westagram/Posting/tests.py
  students/12th/sunghomoon/project_westagram/Posting/urls.py
  students/12th/sunghomoon/project_westagram/Posting/views.py
  students/12th/sunghomoon/project_westagram/manage.py
  students/12th/sunghomoon/project_westagram/project_westagram/__init__.py
  students/12th/sunghomoon/project_westagram/project_westagram/asgi.py
  students/12th/sunghomoon/project_westagram/project_westagram/settings.py
  students/12th/sunghomoon/project_westagram/project_westagram/urls.py
  students/12th/sunghomoon/project_westagram/project_westagram/wsgi.py
  students/12th/sunghomoon/project_westagram/user/__init__.py
  students/12th/sunghomoon/project_westagram/user/admin.py
  students/12th/sunghomoon/project_westagram/user/apps.py
  students/12th/sunghomoon/project_westagram/user/migrations/0001_initial.py
  students/12th/sunghomoon/project_westagram/user/migrations/0002_auto_20200909_0857.py
  students/12th/sunghomoon/project_westagram/user/migrations/__init__.py
  students/12th/sunghomoon/project_westagram/user/models.py
  students/12th/sunghomoon/project_westagram/user/tests.py
  students/12th/sunghomoon/project_westagram/user/urls.py
  students/12th/sunghomoon/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#54 [이수현]인증&인가
  students/12th/soohyunlee/intro.txt
  students/12th/soohyunlee/project_westagram/manage.py
  students/12th/soohyunlee/project_westagram/posting/__init__.py
  students/12th/soohyunlee/project_westagram/posting/admin.py
  students/12th/soohyunlee/project_westagram/posting/apps.py
  students/12th/soohyunlee/project_westagram/posting/migrations/0001_initial.py
  students/12th/soohyunlee/project_westagram/posting/migrations/0002_auto_20200903_0422.py
  students/12th/soohyunlee/project_westagram/posting/migrations/0003_auto_20200903_0738.py
  students/12th/soohyunlee/project_westagram/posting/migrations/0004_posting_writer_people.py
  students/12th/soohyunlee/project_westagram/posting/migrations/__init__.py
  students/12th/soohyunlee/project_westagram/posting/models.py
  students/12th/soohyunlee/project_westagram/posting/tests.py
  students/12th/soohyunlee/project_westagram/posting/urls.py
  students/12th/soohyunlee/project_westagram/posting/views.py
  students/12th/soohyunlee/project_westagram/project_westagram/__init__.py
  students/12th/soohyunlee/project_westagram/project_westagram/asgi.py
  students/12th/soohyunlee/project_westagram/project_westagram/settings.py
  students/12th/soohyunlee/project_westagram/project_westagram/urls.py
  students/12th/soohyunlee/project_westagram/project_westagram/wsgi.py
  students/12th/soohyunlee/project_westagram/urls.py
  students/12th/soohyunlee/project_westagram/user/__init__.py
  students/12th/soohyunlee/project_westagram/user/admin.py
  students/12th/soohyunlee/project_westagram/user/apps.py
  students/12th/soohyunlee/project_westagram/user/migrations/0001_initial.py
  students/12th/soohyunlee/project_westagram/user/migrations/0002_auto_20200902_1345.py
  students/12th/soohyunlee/project_westagram/user/migrations/__init__.py
  students/12th/soohyunlee/project_westagram/user/models.py
  students/12th/soohyunlee/project_westagram/user/tests.py
  students/12th/soohyunlee/project_westagram/user/urls.py
  students/12th/soohyunlee/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#60 [김수현] Mission2. 회원가입 기능 구현
  students/12th/soohyunkim/introduce.txt
  students/12th/soohyunkim/project_westagram/account/__init__.py
  students/12th/soohyunkim/project_westagram/account/admin.py
  students/12th/soohyunkim/project_westagram/account/apps.py
  students/12th/soohyunkim/project_westagram/account/migrations/0001_initial.py
  students/12th/soohyunkim/project_westagram/account/migrations/__init__.py
  students/12th/soohyunkim/project_westagram/account/models.py
  students/12th/soohyunkim/project_westagram/account/tests.py
  students/12th/soohyunkim/project_westagram/account/urls.py
  students/12th/soohyunkim/project_westagram/account/views.py
  students/12th/soohyunkim/project_westagram/manage.py
  students/12th/soohyunkim/project_westagram/project_westagram/__init__.py
  students/12th/soohyunkim/project_westagram/project_westagram/asgi.py
  students/12th/soohyunkim/project_westagram/project_westagram/settings.py
  students/12th/soohyunkim/project_westagram/project_westagram/urls.py
  students/12th/soohyunkim/project_westagram/project_westagram/wsgi.py
  students/12th/soohyunkim/project_westagram/urls.py
  students/12th/soohyunkim/project_westagram/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#63 [김성진] Mission 3: 로그인 endpoint
  students/project_westagram/manage.py
  students/project_westagram/project_westagram/__init__.py
  students/project_westagram/project_westagram/asgi.py
  students/project_westagram/project_westagram/settings.py
  students/project_westagram/project_westagram/urls.py
  students/project_westagram/project_westagram/wsgi.py
  students/project_westagram/user/__init__.py
  students/project_westagram/user/admin.py
  students/project_westagram/user/apps.py
  students/project_westagram/user/migrations/0001_initial.py
  students/project_westagram/user/migrations/__init__.py
  students/project_westagram/user/models.py
  students/project_westagram/user/tests.py
  students/project_westagram/user/urls.py
  students/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#64 [홍성은]Mission3:로그인 엔드포인트
  students/12th/sungeunhong/intro.txt
  students/12th/sungeunhong/project_westagram/manage.py
  students/12th/sungeunhong/project_westagram/project_westagram/__init__.py
  students/12th/sungeunhong/project_westagram/project_westagram/asgi.py
  students/12th/sungeunhong/project_westagram/project_westagram/settings.py
  students/12th/sungeunhong/project_westagram/project_westagram/urls.py
  students/12th/sungeunhong/project_westagram/project_westagram/wsgi.py
  students/12th/sungeunhong/project_westagram/user/__init__.py
  students/12th/sungeunhong/project_westagram/user/admin.py
  students/12th/sungeunhong/project_westagram/user/apps.py
  students/12th/sungeunhong/project_westagram/user/migrations/0001_initial.py
  students/12th/sungeunhong/project_westagram/user/migrations/0002_auto_20200903_0628.py
  students/12th/sungeunhong/project_westagram/user/migrations/0003_auto_20200903_0924.py
  students/12th/sungeunhong/project_westagram/user/migrations/__init__.py
  students/12th/sungeunhong/project_westagram/user/models.py
  students/12th/sungeunhong/project_westagram/user/tests.py
  students/12th/sungeunhong/project_westagram/user/urls.py
  students/12th/sungeunhong/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#65 [구동현] Mission 2. 회원가입 기능 구현
  project_westagram/account/__init__.py
  project_westagram/account/admin.py
  project_westagram/account/apps.py
  project_westagram/account/default
  project_westagram/account/migrations/0001_initial.py
  project_westagram/account/migrations/0002_users_mobile.py
  project_westagram/account/migrations/0003_remove_users_mobile.py
  project_westagram/account/migrations/0004_auto_20200902_0833.py
  project_westagram/account/migrations/__init__.py
  project_westagram/account/models.py
  project_westagram/account/settings.py
  project_westagram/account/tests.py
  project_westagram/account/urls.py
  project_westagram/account/validation.py
  project_westagram/account/views.py
  project_westagram/manage.py
  project_westagram/project_westagram/__init__.py
  project_westagram/project_westagram/asgi.py
  project_westagram/project_westagram/settings.py
  project_westagram/project_westagram/urls.py
  project_westagram/project_westagram/views.py
  project_westagram/project_westagram/wsgi.py
  project_westagram/settings.py
  project_westagram/views.py
  students/12th/introduce.txt
Labels: Status : 리뷰 요청, 필수 구현 사항

#66 [김수정] Mission 4. 게시글 작성
  students/12th/Soojeong/project_westagram/manage.py
  students/12th/Soojeong/project_westagram/posts/__init__.py
  students/12th/Soojeong/project_westagram/posts/admin.py
  students/12th/Soojeong/project_westagram/posts/apps.py
  students/12th/Soojeong/project_westagram/posts/migrations/0001_initial.py
  students/12th/Soojeong/project_westagram/posts/migrations/0002_auto_20200903_1423.py
  students/12th/Soojeong/project_westagram/posts/migrations/0003_posts_pub_content.py
  students/12th/Soojeong/project_westagram/posts/migrations/__init__.py
  students/12th/Soojeong/project_westagram/posts/models.py
  students/12th/Soojeong/project_westagram/posts/tests.py
  students/12th/Soojeong/project_westagram/posts/urls.py
  students/12th/Soojeong/project_westagram/posts/views.py
  students/12th/Soojeong/project_westagram/project_westagram/.gitignore.py
  students/12th/Soojeong/project_westagram/project_westagram/__init__.py
  students/12th/Soojeong/project_westagram/project_westagram/asgi.py
  students/12th/Soojeong/project_westagram/project_westagram/settings.py
  students/12th/Soojeong/project_westagram/project_westagram/urls.py
  students/12th/Soojeong/project_westagram/project_westagram/wsgi.py
  students/12th/Soojeong/project_westagram/user/__init__.py
  students/12th/Soojeong/project_westagram/user/admin.py
  students/12th/Soojeong/project_westagram/user/apps.py
  students/12th/Soojeong/project_westagram/user/migrations/0001_initial.py
  students/12th/Soojeong/project_westagram/user/migrations/0002_auto_20200902_1116.py
  students/12th/Soojeong/project_westagram/user/migrations/0003_auto_20200903_2358.py
  students/12th/Soojeong/project_westagram/user/migrations/0004_auto_20200909_2023.py
  students/12th/Soojeong/project_westagram/user/migrations/0005_auto_20200909_2116.py
  students/12th/Soojeong/project_westagram/user/migrations/__init__.py
  students/12th/Soojeong/project_westagram/user/models.py
  students/12th/Soojeong/project_westagram/user/tests.py
  students/12th/Soojeong/project_westagram/user/urls.py
  students/12th/Soojeong/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#67 [오가빈] [Mission 3] 로그인 엔드포인트
  students/12th/ogabin/project_westagram/manage.py
  students/12th/ogabin/project_westagram/project_westagram/__init__.py
  students/12th/ogabin/project_westagram/project_westagram/asgi.py
  students/12th/ogabin/project_westagram/project_westagram/settings.py
  students/12th/ogabin/project_westagram/project_westagram/urls.py
  students/12th/ogabin/project_westagram/project_westagram/wsgi.py
  students/12th/ogabin/project_westagram/user/__init__.py
  students/12th/ogabin/project_westagram/user/admin.py
  students/12th/ogabin/project_westagram/user/apps.py
  students/12th/ogabin/project_westagram/user/migrations/0001_initial.py
  students/12th/ogabin/project_westagram/user/migrations/__init__.py
  students/12th/ogabin/project_westagram/user/models.py
  students/12th/ogabin/project_westagram/user/tests.py
  students/12th/ogabin/project_westagram/user/urls.py
  students/12th/ogabin/project_westagram/user/validation.py
  students/12th/ogabin/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#51 [이소헌] Add: intro.txt
  students/12th/soheonlee/intro.txt
Labels: Status : 리뷰 요청, 필수 구현 사항

#68 [박현희] Mission 1 : Django 초기 세팅
  students/13th/hyunheepark/westagram/manage.py
  students/13th/hyunheepark/westagram/posting/__init__.py
  students/13th/hyunheepark/westagram/posting/admin.py
  students/13th/hyunheepark/westagram/posting/apps.py
  students/13th/hyunheepark/westagram/posting/migrations/0001_initial.py
  students/13th/hyunheepark/westagram/posting/migrations/0002_auto_20201018_2037.py
  students/13th/hyunheepark/westagram/posting/migrations/__init__.py
  students/13th/hyunheepark/westagram/posting/models.py
  students/13th/hyunheepark/westagram/posting/tests.py
  students/13th/hyunheepark/westagram/posting/urls.py
  students/13th/hyunheepark/westagram/posting/views.py
  students/13th/hyunheepark/westagram/user/__init__.py
  students/13th/hyunheepark/westagram/user/admin.py
  students/13th/hyunheepark/westagram/user/apps.py
  students/13th/hyunheepark/westagram/user/migrations/0001_initial.py
  students/13th/hyunheepark/westagram/user/migrations/__init__.py
  students/13th/hyunheepark/westagram/user/models.py
  students/13th/hyunheepark/westagram/user/tests.py
  students/13th/hyunheepark/westagram/user/urls.py
  students/13th/hyunheepark/westagram/user/views.py
  students/13th/hyunheepark/westagram/westagram/__init__.py
  students/13th/hyunheepark/westagram/westagram/asgi.py
  students/13th/hyunheepark/westagram/westagram/settings.py
  students/13th/hyunheepark/westagram/westagram/urls.py
  students/13th/hyunheepark/westagram/westagram/wsgi.py
Labels: Status : 수정 요청, 필수 구현 사항

#70 [김지훈][Mission 10] 특정 댓글에 대답하는 '대댓글' 달기/인증&인가 구현
  students/13th/jeehoonkim/westagram/.gitignore
  students/13th/jeehoonkim/westagram/.vscode/settings.json
  students/13th/jeehoonkim/westagram/manage.py
  students/13th/jeehoonkim/westagram/post/__init__.py
  students/13th/jeehoonkim/westagram/post/admin.py
  students/13th/jeehoonkim/westagram/post/apps.py
  students/13th/jeehoonkim/westagram/post/migrations/__init__.py
  students/13th/jeehoonkim/westagram/post/models.py
  students/13th/jeehoonkim/westagram/post/tests.py
  students/13th/jeehoonkim/westagram/post/views.py
  students/13th/jeehoonkim/westagram/posting/__init__.py
  students/13th/jeehoonkim/westagram/posting/admin.py
  students/13th/jeehoonkim/westagram/posting/apps.py
  students/13th/jeehoonkim/westagram/posting/migrations/0001_initial.py
  students/13th/jeehoonkim/westagram/posting/migrations/0002_auto_20201009_1106.py
  students/13th/jeehoonkim/westagram/posting/migrations/0003_comment.py
  students/13th/jeehoonkim/westagram/posting/migrations/0004_auto_20201010_0613.py
  students/13th/jeehoonkim/westagram/posting/migrations/0005_comment_thread_to.py
  students/13th/jeehoonkim/westagram/posting/migrations/0006_auto_20201016_0050.py
  students/13th/jeehoonkim/westagram/posting/migrations/0007_remove_posting_like.py
  students/13th/jeehoonkim/westagram/posting/migrations/0008_auto_20201016_0356.py
  students/13th/jeehoonkim/westagram/posting/migrations/0009_auto_20201016_0357.py
  students/13th/jeehoonkim/westagram/posting/migrations/__init__.py
  students/13th/jeehoonkim/westagram/posting/models.py
  students/13th/jeehoonkim/westagram/posting/tests.py
  students/13th/jeehoonkim/westagram/posting/urls.py
  students/13th/jeehoonkim/westagram/posting/views.py
  students/13th/jeehoonkim/westagram/user/__init__.py
  students/13th/jeehoonkim/westagram/user/admin.py
  students/13th/jeehoonkim/westagram/user/apps.py
  students/13th/jeehoonkim/westagram/user/migrations/0001_initial.py
  students/13th/jeehoonkim/westagram/user/migrations/0002_user_follow.py
  students/13th/jeehoonkim/westagram/user/migrations/0003_auto_20201012_0634.py
  students/13th/jeehoonkim/westagram/user/migrations/__init__.py
  students/13th/jeehoonkim/westagram/user/models.py
  students/13th/jeehoonkim/westagram/user/tests.py
  students/13th/jeehoonkim/westagram/user/urls.py
  students/13th/jeehoonkim/westagram/user/utils.py
  students/13th/jeehoonkim/westagram/user/views.py
  students/13th/jeehoonkim/westagram/westagram/__init__.py
  students/13th/jeehoonkim/westagram/westagram/asgi.py
  students/13th/jeehoonkim/westagram/westagram/settings.py
  students/13th/jeehoonkim/westagram/westagram/urls.py
  students/13th/jeehoonkim/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#71 [김창곤][Mission 4] Posting and reading posts
  students/13th/changgonkim/westagram/account/__init__.py
  students/13th/changgonkim/westagram/account/admin.py
  students/13th/changgonkim/westagram/account/apps.py
  students/13th/changgonkim/westagram/account/migrations/0001_initial.py
  students/13th/changgonkim/westagram/account/migrations/0002_auto_20201012_1007.py
  students/13th/changgonkim/westagram/account/migrations/0003_auto_20201012_1008.py
  students/13th/changgonkim/westagram/account/migrations/0004_auto_20201012_1040.py
  students/13th/changgonkim/westagram/account/migrations/0005_auto_20201013_1215.py
  students/13th/changgonkim/westagram/account/migrations/__init__.py
  students/13th/changgonkim/westagram/account/models.py
  students/13th/changgonkim/westagram/account/tests.py
  students/13th/changgonkim/westagram/account/urls.py
  students/13th/changgonkim/westagram/account/views.py
  students/13th/changgonkim/westagram/manage.py
  students/13th/changgonkim/westagram/post/__init__.py
  students/13th/changgonkim/westagram/post/admin.py
  students/13th/changgonkim/westagram/post/apps.py
  students/13th/changgonkim/westagram/post/migrations/0001_initial.py
  students/13th/changgonkim/westagram/post/migrations/0002_auto_20201015_0739.py
  students/13th/changgonkim/westagram/post/migrations/0003_auto_20201015_0741.py
  students/13th/changgonkim/westagram/post/migrations/0004_auto_20201015_0803.py
  students/13th/changgonkim/westagram/post/migrations/__init__.py
  students/13th/changgonkim/westagram/post/models.py
  students/13th/changgonkim/westagram/post/tests.py
  students/13th/changgonkim/westagram/post/urls.py
  students/13th/changgonkim/westagram/post/views.py
  students/13th/changgonkim/westagram/westagram/__init__.py
  students/13th/changgonkim/westagram/westagram/asgi.py
  students/13th/changgonkim/westagram/westagram/settings.py
  students/13th/changgonkim/westagram/westagram/urls.py
  students/13th/changgonkim/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#72 [민경민] Mission 10 : 대댓글 기능 추가
  students/13th/gyeongminmin/westagram/.gitignore
  students/13th/gyeongminmin/westagram/auth/__init__.py
  students/13th/gyeongminmin/westagram/auth/admin.py
  students/13th/gyeongminmin/westagram/auth/apps.py
  students/13th/gyeongminmin/westagram/auth/migrations/0001_initial.py
  students/13th/gyeongminmin/westagram/auth/migrations/__init__.py
  students/13th/gyeongminmin/westagram/auth/models.py
  students/13th/gyeongminmin/westagram/auth/tests.py
  students/13th/gyeongminmin/westagram/auth/urls.py
  students/13th/gyeongminmin/westagram/auth/views.py
  students/13th/gyeongminmin/westagram/manage.py
  students/13th/gyeongminmin/westagram/post/__init__.py
  students/13th/gyeongminmin/westagram/post/admin.py
  students/13th/gyeongminmin/westagram/post/apps.py
  students/13th/gyeongminmin/westagram/post/migrations/0001_initial.py
  students/13th/gyeongminmin/westagram/post/migrations/0002_postimage.py
  students/13th/gyeongminmin/westagram/post/migrations/0003_comments_comment_id.py
  students/13th/gyeongminmin/westagram/post/migrations/0004_auto_20201012_0629.py
  students/13th/gyeongminmin/westagram/post/migrations/0005_auto_20201012_0631.py
  students/13th/gyeongminmin/westagram/post/migrations/0006_auto_20201012_1037.py
  students/13th/gyeongminmin/westagram/post/migrations/0007_auto_20201012_1045.py
  students/13th/gyeongminmin/westagram/post/migrations/0008_auto_20201012_1235.py
  students/13th/gyeongminmin/westagram/post/migrations/0009_recomments.py
  students/13th/gyeongminmin/westagram/post/migrations/__init__.py
  students/13th/gyeongminmin/westagram/post/models.py
  students/13th/gyeongminmin/westagram/post/tests.py
  students/13th/gyeongminmin/westagram/post/urls.py
  students/13th/gyeongminmin/westagram/post/views.py
  students/13th/gyeongminmin/westagram/utils.py
  students/13th/gyeongminmin/westagram/westagram/__init__.py
  students/13th/gyeongminmin/westagram/westagram/asgi.py
  students/13th/gyeongminmin/westagram/westagram/settings.py
  students/13th/gyeongminmin/westagram/westagram/urls.py
  students/13th/gyeongminmin/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#73 [김동현] [Mission 10] 특정 댓글에 대답하는 '대댓글' 달기 / 인증 인가
  students/13th/donghyeonkim/westargram/like/__init__.py
  students/13th/donghyeonkim/westargram/like/admin.py
  students/13th/donghyeonkim/westargram/like/apps.py
  students/13th/donghyeonkim/westargram/like/migrations/0001_initial.py
  students/13th/donghyeonkim/westargram/like/migrations/0002_delete_like.py
  students/13th/donghyeonkim/westargram/like/migrations/__init__.py
  students/13th/donghyeonkim/westargram/like/models.py
  students/13th/donghyeonkim/westargram/like/tests.py
  students/13th/donghyeonkim/westargram/like/urls.py
  students/13th/donghyeonkim/westargram/like/views.py
  students/13th/donghyeonkim/westargram/manage.py
  students/13th/donghyeonkim/westargram/posting/__init__.py
  students/13th/donghyeonkim/westargram/posting/admin.py
  students/13th/donghyeonkim/westargram/posting/apps.py
  students/13th/donghyeonkim/westargram/posting/migrations/0001_initial.py
  students/13th/donghyeonkim/westargram/posting/migrations/0002_comment.py
  students/13th/donghyeonkim/westargram/posting/migrations/0003_post_likes.py
  students/13th/donghyeonkim/westargram/posting/migrations/0004_comment_response_to.py
  students/13th/donghyeonkim/westargram/posting/migrations/__init__.py
  students/13th/donghyeonkim/westargram/posting/models.py
  students/13th/donghyeonkim/westargram/posting/tests.py
  students/13th/donghyeonkim/westargram/posting/urls.py
  students/13th/donghyeonkim/westargram/posting/views.py
  students/13th/donghyeonkim/westargram/user/__init__.py
  students/13th/donghyeonkim/westargram/user/admin.py
  students/13th/donghyeonkim/westargram/user/apps.py
  students/13th/donghyeonkim/westargram/user/migrations/0001_initial.py
  students/13th/donghyeonkim/westargram/user/migrations/0002_auto_20201009_1804.py
  students/13th/donghyeonkim/westargram/user/migrations/0003_remove_user_phone_number.py
  students/13th/donghyeonkim/westargram/user/migrations/0004_auto_20201009_2004.py
  students/13th/donghyeonkim/westargram/user/migrations/0005_user_follow.py
  students/13th/donghyeonkim/westargram/user/migrations/0006_auto_20201012_1632.py
  students/13th/donghyeonkim/westargram/user/migrations/0007_auto_20201013_1510.py
  students/13th/donghyeonkim/westargram/user/migrations/__init__.py
  students/13th/donghyeonkim/westargram/user/models.py
  students/13th/donghyeonkim/westargram/user/tests.py
  students/13th/donghyeonkim/westargram/user/urls.py
  students/13th/donghyeonkim/westargram/user/utils.py
  students/13th/donghyeonkim/westargram/user/views.py
  students/13th/donghyeonkim/westargram/westargram/__init__.py
  students/13th/donghyeonkim/westargram/westargram/asgi.py
  students/13th/donghyeonkim/westargram/westargram/settings.py
  students/13th/donghyeonkim/westargram/westargram/urls.py
  students/13th/donghyeonkim/westargram/westargram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#74 [김성태] [Mission 6] 게시물 '좋아요' 기능 구현
  students/13th/seongtaekim/project_westagram/manage.py
  students/13th/seongtaekim/project_westagram/posting/__init__.py
  students/13th/seongtaekim/project_westagram/posting/admin.py
  students/13th/seongtaekim/project_westagram/posting/apps.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0001_initial.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0002_auto_20201012_1601.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0003_auto_20201013_1704.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0004_like.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0005_auto_20201013_2100.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0006_auto_20201013_2102.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0007_auto_20201013_2143.py
  students/13th/seongtaekim/project_westagram/posting/migrations/0008_auto_20201015_1523.py
  students/13th/seongtaekim/project_westagram/posting/migrations/__init__.py
  students/13th/seongtaekim/project_westagram/posting/models.py
  students/13th/seongtaekim/project_westagram/posting/tests.py
  students/13th/seongtaekim/project_westagram/posting/urls.py
  students/13th/seongtaekim/project_westagram/posting/views.py
  students/13th/seongtaekim/project_westagram/project_westagram/__init__.py
  students/13th/seongtaekim/project_westagram/project_westagram/asgi.py
  students/13th/seongtaekim/project_westagram/project_westagram/settings.py
  students/13th/seongtaekim/project_westagram/project_westagram/urls.py
  students/13th/seongtaekim/project_westagram/project_westagram/wsgi.py
  students/13th/seongtaekim/project_westagram/user/__init__.py
  students/13th/seongtaekim/project_westagram/user/admin.py
  students/13th/seongtaekim/project_westagram/user/apps.py
  students/13th/seongtaekim/project_westagram/user/migrations/0001_initial.py
  students/13th/seongtaekim/project_westagram/user/migrations/0002_auto_20201010_1004.py
  students/13th/seongtaekim/project_westagram/user/migrations/0003_auto_20201011_0541.py
  students/13th/seongtaekim/project_westagram/user/migrations/0004_auto_20201011_0544.py
  students/13th/seongtaekim/project_westagram/user/migrations/0005_auto_20201011_0619.py
  students/13th/seongtaekim/project_westagram/user/migrations/0006_image_urls_post.py
  students/13th/seongtaekim/project_westagram/user/migrations/0007_auto_20201011_2041.py
  students/13th/seongtaekim/project_westagram/user/migrations/0008_auto_20201011_2130.py
  students/13th/seongtaekim/project_westagram/user/migrations/0009_auto_20201012_2220.py
  students/13th/seongtaekim/project_westagram/user/migrations/0010_auto_20201013_1537.py
  students/13th/seongtaekim/project_westagram/user/migrations/0011_auto_20201013_2237.py
  students/13th/seongtaekim/project_westagram/user/migrations/0012_auto_20201013_2238.py
  students/13th/seongtaekim/project_westagram/user/migrations/0013_auto_20201015_1523.py
  students/13th/seongtaekim/project_westagram/user/migrations/0014_auto_20201015_1525.py
  students/13th/seongtaekim/project_westagram/user/migrations/__init__.py
  students/13th/seongtaekim/project_westagram/user/models.py
  students/13th/seongtaekim/project_westagram/user/tests.py
  students/13th/seongtaekim/project_westagram/user/urls.py
  students/13th/seongtaekim/project_westagram/user/utils.py
  students/13th/seongtaekim/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#76 [황채영][Mission 10] 인증 인가
  students/13th/chaeyeonghwang/project_westagram/.vscode/settings.json
  students/13th/chaeyeonghwang/project_westagram/manage.py
  students/13th/chaeyeonghwang/project_westagram/posting/__init__.py
  students/13th/chaeyeonghwang/project_westagram/posting/admin.py
  students/13th/chaeyeonghwang/project_westagram/posting/apps.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/0001_initial.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/0002_auto_20201010_1537.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/0003_comment.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/0004_auto_20201010_1957.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/0005_like.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/0006_reply.py
  students/13th/chaeyeonghwang/project_westagram/posting/migrations/__init__.py
  students/13th/chaeyeonghwang/project_westagram/posting/models.py
  students/13th/chaeyeonghwang/project_westagram/posting/urls.py
  students/13th/chaeyeonghwang/project_westagram/posting/views.py
  students/13th/chaeyeonghwang/project_westagram/project_westagram/__init__.py
  students/13th/chaeyeonghwang/project_westagram/project_westagram/asgi.py
  students/13th/chaeyeonghwang/project_westagram/project_westagram/settings.py
  students/13th/chaeyeonghwang/project_westagram/project_westagram/urls.py
  students/13th/chaeyeonghwang/project_westagram/project_westagram/wsgi.py
  students/13th/chaeyeonghwang/project_westagram/user/__init__.py
  students/13th/chaeyeonghwang/project_westagram/user/admin.py
  students/13th/chaeyeonghwang/project_westagram/user/apps.py
  students/13th/chaeyeonghwang/project_westagram/user/migrations/0001_initial.py
  students/13th/chaeyeonghwang/project_westagram/user/migrations/0002_auto_20201009_0648.py
  students/13th/chaeyeonghwang/project_westagram/user/migrations/0003_user_follow.py
  students/13th/chaeyeonghwang/project_westagram/user/migrations/0004_auto_20201014_1727.py
  students/13th/chaeyeonghwang/project_westagram/user/migrations/__init__.py
  students/13th/chaeyeonghwang/project_westagram/user/models.py
  students/13th/chaeyeonghwang/project_westagram/user/urls.py
  students/13th/chaeyeonghwang/project_westagram/user/utils.py
  students/13th/chaeyeonghwang/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#77 [성규원] [Mission 6] 게시글 좋아요 기능 구현
  students/13th/Gyuwon/project_westagram/.vscode/settings.json
  students/13th/Gyuwon/project_westagram/manage.py
  students/13th/Gyuwon/project_westagram/post/__init__.py
  students/13th/Gyuwon/project_westagram/post/admin.py
  students/13th/Gyuwon/project_westagram/post/apps.py
  students/13th/Gyuwon/project_westagram/post/migrations/0001_initial.py
  students/13th/Gyuwon/project_westagram/post/migrations/0002_auto_20201013_0932.py
  students/13th/Gyuwon/project_westagram/post/migrations/0003_auto_20201013_1004.py
  students/13th/Gyuwon/project_westagram/post/migrations/0004_auto_20201013_1037.py
  students/13th/Gyuwon/project_westagram/post/migrations/0005_auto_20201015_0422.py
  students/13th/Gyuwon/project_westagram/post/migrations/0006_like.py
  students/13th/Gyuwon/project_westagram/post/migrations/__init__.py
  students/13th/Gyuwon/project_westagram/post/models.py
  students/13th/Gyuwon/project_westagram/post/tests.py
  students/13th/Gyuwon/project_westagram/post/urls.py
  students/13th/Gyuwon/project_westagram/post/views.py
  students/13th/Gyuwon/project_westagram/project_westagram/__init__.py
  students/13th/Gyuwon/project_westagram/project_westagram/asgi.py
  students/13th/Gyuwon/project_westagram/project_westagram/settings.py
  students/13th/Gyuwon/project_westagram/project_westagram/urls.py
  students/13th/Gyuwon/project_westagram/project_westagram/wsgi.py
  students/13th/Gyuwon/project_westagram/user/__init__.py
  students/13th/Gyuwon/project_westagram/user/admin.py
  students/13th/Gyuwon/project_westagram/user/apps.py
  students/13th/Gyuwon/project_westagram/user/migrations/0001_initial.py
  students/13th/Gyuwon/project_westagram/user/migrations/0002_auto_20201013_1635.py
  students/13th/Gyuwon/project_westagram/user/migrations/0003_auto_20201013_1709.py
  students/13th/Gyuwon/project_westagram/user/migrations/0004_auto_20201016_0113.py
  students/13th/Gyuwon/project_westagram/user/migrations/__init__.py
  students/13th/Gyuwon/project_westagram/user/models.py
  students/13th/Gyuwon/project_westagram/user/tests.py
  students/13th/Gyuwon/project_westagram/user/urls.py
  students/13th/Gyuwon/project_westagram/user/views.py
Labels: Status : 수정 요청, 추가 구현 사항, 필수 구현 사항

#78 [김예진][Mission3]비밀번호 암호화, 토큰 생성 전달
  students/13th/kimyejin/project_westagram/manage.py
  students/13th/kimyejin/project_westagram/project_westagram/__init__.py
  students/13th/kimyejin/project_westagram/project_westagram/asgi.py
  students/13th/kimyejin/project_westagram/project_westagram/settings.py
  students/13th/kimyejin/project_westagram/project_westagram/urls.py
  students/13th/kimyejin/project_westagram/project_westagram/wsgi.py
  students/13th/kimyejin/project_westagram/settings.py
  students/13th/kimyejin/project_westagram/user/__init__.py
  students/13th/kimyejin/project_westagram/user/admin.py
  students/13th/kimyejin/project_westagram/user/apps.py
  students/13th/kimyejin/project_westagram/user/migrations/0001_initial.py
  students/13th/kimyejin/project_westagram/user/migrations/0002_auto_20201015_0843.py
  students/13th/kimyejin/project_westagram/user/migrations/__init__.py
  students/13th/kimyejin/project_westagram/user/models.py
  students/13th/kimyejin/project_westagram/user/tests.py
  students/13th/kimyejin/project_westagram/user/urls.py
  students/13th/kimyejin/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#79 [허소정] [Mission 4] 게시물 등록
  students/13th/sojeongheo/westagram/manage.py
  students/13th/sojeongheo/westagram/posting/__init__.py
  students/13th/sojeongheo/westagram/posting/admin.py
  students/13th/sojeongheo/westagram/posting/apps.py
  students/13th/sojeongheo/westagram/posting/migrations/0001_initial.py
  students/13th/sojeongheo/westagram/posting/migrations/0002_posting_contents.py
  students/13th/sojeongheo/westagram/posting/migrations/__init__.py
  students/13th/sojeongheo/westagram/posting/models.py
  students/13th/sojeongheo/westagram/posting/tests.py
  students/13th/sojeongheo/westagram/posting/urls.py
  students/13th/sojeongheo/westagram/posting/views.py
  students/13th/sojeongheo/westagram/user/__init__.py
  students/13th/sojeongheo/westagram/user/admin.py
  students/13th/sojeongheo/westagram/user/apps.py
  students/13th/sojeongheo/westagram/user/migrations/0001_initial.py
  students/13th/sojeongheo/westagram/user/migrations/0002_auto_20201012_0640.py
  students/13th/sojeongheo/westagram/user/migrations/0003_auto_20201013_0250.py
  students/13th/sojeongheo/westagram/user/migrations/0004_auto_20201013_0657.py
  students/13th/sojeongheo/westagram/user/migrations/0005_auto_20201013_1214.py
  students/13th/sojeongheo/westagram/user/migrations/__init__.py
  students/13th/sojeongheo/westagram/user/models.py
  students/13th/sojeongheo/westagram/user/tests.py
  students/13th/sojeongheo/westagram/user/urls.py
  students/13th/sojeongheo/westagram/user/views.py
  students/13th/sojeongheo/westagram/westagram/__init__.py
  students/13th/sojeongheo/westagram/westagram/asgi.py
  students/13th/sojeongheo/westagram/westagram/settings.py
  students/13th/sojeongheo/westagram/westagram/urls.py
  students/13th/sojeongheo/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#80 [박재용}[Mission 2] 회원가입 엔드포인트 #24
  students/13th/parkjaeyong/project_westagram/.gitignore
  students/13th/parkjaeyong/project_westagram/manage.py
  students/13th/parkjaeyong/project_westagram/project_westagram/.gitignore
  students/13th/parkjaeyong/project_westagram/project_westagram/__init__.py
  students/13th/parkjaeyong/project_westagram/project_westagram/asgi.py
  students/13th/parkjaeyong/project_westagram/project_westagram/settings.py
  students/13th/parkjaeyong/project_westagram/project_westagram/urls.py
  students/13th/parkjaeyong/project_westagram/project_westagram/wsgi.py
  students/13th/parkjaeyong/project_westagram/user/__init__.py
  students/13th/parkjaeyong/project_westagram/user/admin.py
  students/13th/parkjaeyong/project_westagram/user/apps.py
  students/13th/parkjaeyong/project_westagram/user/migrations/0001_initial.py
  students/13th/parkjaeyong/project_westagram/user/migrations/0002_auto_20201014_0837.py
  students/13th/parkjaeyong/project_westagram/user/migrations/0003_auto_20201015_0600.py
  students/13th/parkjaeyong/project_westagram/user/migrations/__init__.py
  students/13th/parkjaeyong/project_westagram/user/models.py
  students/13th/parkjaeyong/project_westagram/user/tests.py
  students/13th/parkjaeyong/project_westagram/user/urls.py
  students/13th/parkjaeyong/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#81 [정승호] [Mission 3] 로그인 엔드포인트
  students/13th/seunghojeong/project_westagram/project_westagram/manage.py
  students/13th/seunghojeong/project_westagram/project_westagram/project_westagram/__init__.py
  students/13th/seunghojeong/project_westagram/project_westagram/project_westagram/asgi.py
  students/13th/seunghojeong/project_westagram/project_westagram/project_westagram/settings.py
  students/13th/seunghojeong/project_westagram/project_westagram/project_westagram/urls.py
  students/13th/seunghojeong/project_westagram/project_westagram/project_westagram/wsgi.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/__init__.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/admin.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/apps.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/migrations/0001_initial.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/migrations/__init__.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/models.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/tests.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/urls.py
  students/13th/seunghojeong/project_westagram/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#104 [14강두연][Mission 1~10] 완료
  .gitignore
  students/14th/team2/dooyeon-kang/project_westagram/manage.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/__init__.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/admin.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/apps.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/migrations/0001_initial.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/migrations/0002_auto_20201105_1136.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/migrations/0003_auto_20201109_1351.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/migrations/0004_auto_20201109_1934.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/migrations/0005_comment_reply_on.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/migrations/__init__.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/models.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/tests.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/urls.py
  students/14th/team2/dooyeon-kang/project_westagram/posting/views.py
  students/14th/team2/dooyeon-kang/project_westagram/project_westagram/__init__.py
  students/14th/team2/dooyeon-kang/project_westagram/project_westagram/asgi.py
  students/14th/team2/dooyeon-kang/project_westagram/project_westagram/settings.py
  students/14th/team2/dooyeon-kang/project_westagram/project_westagram/urls.py
  students/14th/team2/dooyeon-kang/project_westagram/project_westagram/wsgi.py
  students/14th/team2/dooyeon-kang/project_westagram/user/__init__.py
  students/14th/team2/dooyeon-kang/project_westagram/user/admin.py
  students/14th/team2/dooyeon-kang/project_westagram/user/apps.py
  students/14th/team2/dooyeon-kang/project_westagram/user/migrations/0001_initial.py
  students/14th/team2/dooyeon-kang/project_westagram/user/migrations/0002_auto_20201109_1351.py
  students/14th/team2/dooyeon-kang/project_westagram/user/migrations/0003_auto_20201109_1934.py
  students/14th/team2/dooyeon-kang/project_westagram/user/migrations/0004_auto_20201110_1405.py
  students/14th/team2/dooyeon-kang/project_westagram/user/migrations/__init__.py
  students/14th/team2/dooyeon-kang/project_westagram/user/models.py
  students/14th/team2/dooyeon-kang/project_westagram/user/tests.py
  students/14th/team2/dooyeon-kang/project_westagram/user/urls.py
  students/14th/team2/dooyeon-kang/project_westagram/user/utils.py
  students/14th/team2/dooyeon-kang/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#105 Add: issue 1 부터 5 까지 작업본 최초 추가
  students/14th/team_1/seungjin/project_westagram/.idea/inspectionProfiles/profiles_settings.xml
  students/14th/team_1/seungjin/project_westagram/.idea/misc.xml
  students/14th/team_1/seungjin/project_westagram/.idea/modules.xml
  students/14th/team_1/seungjin/project_westagram/.idea/project_westagram.iml
  students/14th/team_1/seungjin/project_westagram/.idea/vcs.xml
  students/14th/team_1/seungjin/project_westagram/.idea/workspace.xml
  students/14th/team_1/seungjin/project_westagram/manage.py
  students/14th/team_1/seungjin/project_westagram/posting/__init__.py
  students/14th/team_1/seungjin/project_westagram/posting/admin.py
  students/14th/team_1/seungjin/project_westagram/posting/apps.py
  students/14th/team_1/seungjin/project_westagram/posting/migrations/0001_initial.py
  students/14th/team_1/seungjin/project_westagram/posting/migrations/__init__.py
  students/14th/team_1/seungjin/project_westagram/posting/models.py
  students/14th/team_1/seungjin/project_westagram/posting/urls.py
  students/14th/team_1/seungjin/project_westagram/posting/views.py
  students/14th/team_1/seungjin/project_westagram/project_westagram/__init__.py
  students/14th/team_1/seungjin/project_westagram/project_westagram/asgi.py
  students/14th/team_1/seungjin/project_westagram/project_westagram/settings.py
  students/14th/team_1/seungjin/project_westagram/project_westagram/urls.py
  students/14th/team_1/seungjin/project_westagram/project_westagram/wsgi.py
  students/14th/team_1/seungjin/project_westagram/readme.md
  students/14th/team_1/seungjin/project_westagram/share/utils.py
  students/14th/team_1/seungjin/project_westagram/user/__init__.py
  students/14th/team_1/seungjin/project_westagram/user/admin.py
  students/14th/team_1/seungjin/project_westagram/user/apps.py
  students/14th/team_1/seungjin/project_westagram/user/migrations/0001_initial.py
  students/14th/team_1/seungjin/project_westagram/user/migrations/__init__.py
  students/14th/team_1/seungjin/project_westagram/user/models.py
  students/14th/team_1/seungjin/project_westagram/user/tests.py
  students/14th/team_1/seungjin/project_westagram/user/urls.py
  students/14th/team_1/seungjin/project_westagram/user/views.py
Labels: Status : 수정 요청

#106 Add: mission1부터 3까지 작업
  students/14th/team3/minyoung/project_westagram/manage.py
  students/14th/team3/minyoung/project_westagram/project_westagram/__init__.py
  students/14th/team3/minyoung/project_westagram/project_westagram/asgi.py
  students/14th/team3/minyoung/project_westagram/project_westagram/settings.py
  students/14th/team3/minyoung/project_westagram/project_westagram/urls.py
  students/14th/team3/minyoung/project_westagram/project_westagram/wsgi.py
  students/14th/team3/minyoung/project_westagram/user/__init__.py
  students/14th/team3/minyoung/project_westagram/user/admin.py
  students/14th/team3/minyoung/project_westagram/user/apps.py
  students/14th/team3/minyoung/project_westagram/user/migrations/0001_initial.py
  students/14th/team3/minyoung/project_westagram/user/migrations/__init__.py
  students/14th/team3/minyoung/project_westagram/user/models.py
  students/14th/team3/minyoung/project_westagram/user/tests.py
  students/14th/team3/minyoung/project_westagram/user/urls.py
  students/14th/team3/minyoung/project_westagram/user/views.py
Labels: Status : 수정 요청, 필수 구현 사항

#107 [미션3] User 회원가입, 로그인 view, model 작성 14기 신재훈
  students/14th/team3/westagram_folder/manage.py
  students/14th/team3/westagram_folder/posting/__init__.py
  students/14th/team3/westagram_folder/posting/admin.py
  students/14th/team3/westagram_folder/posting/apps.py
  students/14th/team3/westagram_folder/posting/migrations/0001_initial.py
  students/14th/team3/westagram_folder/posting/migrations/0002_auto_20201115_2122.py
  students/14th/team3/westagram_folder/posting/migrations/0003_auto_20201115_2337.py
  students/14th/team3/westagram_folder/posting/migrations/0004_auto_20201115_2341.py
  students/14th/team3/westagram_folder/posting/migrations/__init__.py
  students/14th/team3/westagram_folder/posting/models.py
  students/14th/team3/westagram_folder/posting/tests.py
  students/14th/team3/westagram_folder/posting/urls.py
  students/14th/team3/westagram_folder/posting/views.py
  students/14th/team3/westagram_folder/project_westagram/.gitignore
  students/14th/team3/westagram_folder/project_westagram/:
  students/14th/team3/westagram_folder/project_westagram/__init__.py
  students/14th/team3/westagram_folder/project_westagram/asgi.py
  students/14th/team3/westagram_folder/project_westagram/requirements.txt
  students/14th/team3/westagram_folder/project_westagram/secret.json
  students/14th/team3/westagram_folder/project_westagram/settings.py
  students/14th/team3/westagram_folder/project_westagram/urls.py
  students/14th/team3/westagram_folder/project_westagram/wsgi.py
  students/14th/team3/westagram_folder/user/__init__.py
  students/14th/team3/westagram_folder/user/admin.py
  students/14th/team3/westagram_folder/user/apps.py
  students/14th/team3/westagram_folder/user/migrations/0001_initial.py
  students/14th/team3/westagram_folder/user/migrations/0002_auto_20201105_1232.py
  students/14th/team3/westagram_folder/user/migrations/0003_auto_20201105_1327.py
  students/14th/team3/westagram_folder/user/migrations/0004_auto_20201106_1112.py
  students/14th/team3/westagram_folder/user/migrations/0005_auto_20201106_1142.py
  students/14th/team3/westagram_folder/user/migrations/0006_auto_20201106_1148.py
  students/14th/team3/westagram_folder/user/migrations/0007_auto_20201108_0444.py
  students/14th/team3/westagram_folder/user/migrations/0008_auto_20201109_1125.py
  students/14th/team3/westagram_folder/user/migrations/0009_auto_20201109_1139.py
  students/14th/team3/westagram_folder/user/migrations/__init__.py
  students/14th/team3/westagram_folder/user/models.py
  students/14th/team3/westagram_folder/user/tests.py
  students/14th/team3/westagram_folder/user/urls.py
  students/14th/team3/westagram_folder/user/utils.py
  students/14th/team3/westagram_folder/user/views.py
Labels: Status : 수정 요청, 필수 구현 사항

#109 [14기_장규석] mission 1, 2, 3, 4, 5 작성
  students/14th/team_6/gyuseok/project_westagram/.gitignore
  students/14th/team_6/gyuseok/project_westagram/README.md
  students/14th/team_6/gyuseok/project_westagram/manage.py
  students/14th/team_6/gyuseok/project_westagram/posting/__init__.py
  students/14th/team_6/gyuseok/project_westagram/posting/admin.py
  students/14th/team_6/gyuseok/project_westagram/posting/apps.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0001_initial.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0002_comment.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0003_auto_20201108_2246.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0004_auto_20201109_1336.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0005_auto_20201110_1312.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0006_auto_20201112_1741.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0007_like.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/0008_auto_20201113_0004.py
  students/14th/team_6/gyuseok/project_westagram/posting/migrations/__init__.py
  students/14th/team_6/gyuseok/project_westagram/posting/models.py
  students/14th/team_6/gyuseok/project_westagram/posting/tests.py
  students/14th/team_6/gyuseok/project_westagram/posting/urls.py
  students/14th/team_6/gyuseok/project_westagram/posting/views.py
  students/14th/team_6/gyuseok/project_westagram/project_westagram/__init__.py
  students/14th/team_6/gyuseok/project_westagram/project_westagram/asgi.py
  students/14th/team_6/gyuseok/project_westagram/project_westagram/settings.py
  students/14th/team_6/gyuseok/project_westagram/project_westagram/urls.py
  students/14th/team_6/gyuseok/project_westagram/project_westagram/utils.py
  students/14th/team_6/gyuseok/project_westagram/project_westagram/wsgi.py
  students/14th/team_6/gyuseok/project_westagram/user/__init__.py
  students/14th/team_6/gyuseok/project_westagram/user/admin.py
  students/14th/team_6/gyuseok/project_westagram/user/apps.py
  students/14th/team_6/gyuseok/project_westagram/user/migrations/0001_initial.py
  students/14th/team_6/gyuseok/project_westagram/user/migrations/0002_auto_20201110_1312.py
  students/14th/team_6/gyuseok/project_westagram/user/migrations/__init__.py
  students/14th/team_6/gyuseok/project_westagram/user/models.py
  students/14th/team_6/gyuseok/project_westagram/user/tests.py
  students/14th/team_6/gyuseok/project_westagram/user/urls.py
  students/14th/team_6/gyuseok/project_westagram/user/utils.py
  students/14th/team_6/gyuseok/project_westagram/user/views.py
Labels: Status : 수정 요청

#111 [14th 김정식]mission 1,2,3 구현 + 4, auth 구현
  students/14th/team4/jeongsikkim/project_westagram/.gitignore
  students/14th/team4/jeongsikkim/project_westagram/core/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/core/admin.py
  students/14th/team4/jeongsikkim/project_westagram/core/apps.py
  students/14th/team4/jeongsikkim/project_westagram/core/migrations/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/core/models.py
  students/14th/team4/jeongsikkim/project_westagram/core/my_settings_temp.py
  students/14th/team4/jeongsikkim/project_westagram/core/tests.py
  students/14th/team4/jeongsikkim/project_westagram/core/utils.py
  students/14th/team4/jeongsikkim/project_westagram/core/views.py
  students/14th/team4/jeongsikkim/project_westagram/manage.py
  students/14th/team4/jeongsikkim/project_westagram/posting/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/posting/admin.py
  students/14th/team4/jeongsikkim/project_westagram/posting/apps.py
  students/14th/team4/jeongsikkim/project_westagram/posting/migrations/0001_initial.py
  students/14th/team4/jeongsikkim/project_westagram/posting/migrations/0002_auto_20201109_1600.py
  students/14th/team4/jeongsikkim/project_westagram/posting/migrations/0003_auto_20201109_2110.py
  students/14th/team4/jeongsikkim/project_westagram/posting/migrations/0004_auto_20201113_2142.py
  students/14th/team4/jeongsikkim/project_westagram/posting/migrations/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/posting/models.py
  students/14th/team4/jeongsikkim/project_westagram/posting/tests.py
  students/14th/team4/jeongsikkim/project_westagram/posting/urls.py
  students/14th/team4/jeongsikkim/project_westagram/posting/views.py
  students/14th/team4/jeongsikkim/project_westagram/project_westagram/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/project_westagram/asgi.py
  students/14th/team4/jeongsikkim/project_westagram/project_westagram/settings.py
  students/14th/team4/jeongsikkim/project_westagram/project_westagram/urls.py
  students/14th/team4/jeongsikkim/project_westagram/project_westagram/wsgi.py
  students/14th/team4/jeongsikkim/project_westagram/user/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/user/admin.py
  students/14th/team4/jeongsikkim/project_westagram/user/apps.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0001_initial.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0002_auto_20201105_0648.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0003_auto_20201105_1300.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0004_auto_20201106_0052.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0005_login.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0006_auto_20201106_0716.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0007_auto_20201107_1428.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/0008_auto_20201110_1552.py
  students/14th/team4/jeongsikkim/project_westagram/user/migrations/__init__.py
  students/14th/team4/jeongsikkim/project_westagram/user/models.py
  students/14th/team4/jeongsikkim/project_westagram/user/tests.py
  students/14th/team4/jeongsikkim/project_westagram/user/urls.py
  students/14th/team4/jeongsikkim/project_westagram/user/utils.py
  students/14th/team4/jeongsikkim/project_westagram/user/views.py
  students/14th/team4/test-jeongsik.md
  students/14th/team4/test.md
Labels: Status : 리뷰 요청

#114 Feature/14giyong
  students/14th/team9/giyong-gim/core/__init__.py
  students/14th/team9/giyong-gim/core/admin.py
  students/14th/team9/giyong-gim/core/apps.py
  students/14th/team9/giyong-gim/core/migrations/__init__.py
  students/14th/team9/giyong-gim/core/models.py
  students/14th/team9/giyong-gim/core/tests.py
  students/14th/team9/giyong-gim/core/utils.py
  students/14th/team9/giyong-gim/core/views.py
  students/14th/team9/giyong-gim/manage.py
  students/14th/team9/giyong-gim/post/__init__.py
  students/14th/team9/giyong-gim/post/admin.py
  students/14th/team9/giyong-gim/post/apps.py
  students/14th/team9/giyong-gim/post/migrations/0001_initial.py
  students/14th/team9/giyong-gim/post/migrations/__init__.py
  students/14th/team9/giyong-gim/post/models.py
  students/14th/team9/giyong-gim/post/tests.py
  students/14th/team9/giyong-gim/post/urls.py
  students/14th/team9/giyong-gim/post/views.py
  students/14th/team9/giyong-gim/user/__init__.py
  students/14th/team9/giyong-gim/user/admin.py
  students/14th/team9/giyong-gim/user/apps.py
  students/14th/team9/giyong-gim/user/migrations/0001_initial.py
  students/14th/team9/giyong-gim/user/migrations/__init__.py
  students/14th/team9/giyong-gim/user/models.py
  students/14th/team9/giyong-gim/user/tests.py
  students/14th/team9/giyong-gim/user/urls.py
  students/14th/team9/giyong-gim/user/views.py
  students/14th/team9/giyong-gim/westagram/__init__.py
  students/14th/team9/giyong-gim/westagram/asgi.py
  students/14th/team9/giyong-gim/westagram/settings.py
  students/14th/team9/giyong-gim/westagram/urls.py
  students/14th/team9/giyong-gim/westagram/wsgi.py
Labels: Status : 수정 요청, 필수 구현 사항

#116 로그인창까지 생성 /박승제
  students/14th/team_1/seungje/project_westagram/account/'
  students/14th/team_1/seungje/project_westagram/account/__init__.py
  students/14th/team_1/seungje/project_westagram/account/admin.py
  students/14th/team_1/seungje/project_westagram/account/apps.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0001_initial.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0002_auto_20201105_1659.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0003_auto_20201105_1702.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0004_auto_20201106_0326.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0005_auto_20201106_0333.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0006_auto_20201106_1202.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0007_auto_20201106_1204.py
  students/14th/team_1/seungje/project_westagram/account/migrations/0008_auto_20201107_0833.py
  students/14th/team_1/seungje/project_westagram/account/migrations/__init__.py
  students/14th/team_1/seungje/project_westagram/account/models.py
  students/14th/team_1/seungje/project_westagram/account/tests.py
  students/14th/team_1/seungje/project_westagram/account/urls.py
  students/14th/team_1/seungje/project_westagram/account/views.py
  students/14th/team_1/seungje/project_westagram/manage.py
  students/14th/team_1/seungje/project_westagram/project_westagram/__init__.py
  students/14th/team_1/seungje/project_westagram/project_westagram/asgi.py
  students/14th/team_1/seungje/project_westagram/project_westagram/settings.py
  students/14th/team_1/seungje/project_westagram/project_westagram/urls.py
  students/14th/team_1/seungje/project_westagram/project_westagram/wsgi.py
Labels: Status : 수정 요청

#115 회원가입, 로그인
  students/14th/team9/youngjoo/project_westargram/account/__init__.py
  students/14th/team9/youngjoo/project_westargram/account/admin.py
  students/14th/team9/youngjoo/project_westargram/account/apps.py
  students/14th/team9/youngjoo/project_westargram/account/migrations/0001_initial.py
  students/14th/team9/youngjoo/project_westargram/account/migrations/__init__.py
  students/14th/team9/youngjoo/project_westargram/account/models.py
  students/14th/team9/youngjoo/project_westargram/account/tests.py
  students/14th/team9/youngjoo/project_westargram/account/urls.py
  students/14th/team9/youngjoo/project_westargram/account/views.py
  students/14th/team9/youngjoo/project_westargram/manage.py
  students/14th/team9/youngjoo/project_westargram/project_westargram/__init__.py
  students/14th/team9/youngjoo/project_westargram/project_westargram/asgi.py
  students/14th/team9/youngjoo/project_westargram/project_westargram/settings.py
  students/14th/team9/youngjoo/project_westargram/project_westargram/urls.py
  students/14th/team9/youngjoo/project_westargram/project_westargram/wsgi.py
Labels: Status : 수정 요청

#118 14기 백승찬 part6~part7
  students/14th/team_05/seungchan-baek/project_westagram/.vscode/settings.json
  students/14th/team_05/seungchan-baek/project_westagram/follow/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/admin.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/apps.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/migrations/0001_initial.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/migrations/0002_auto_20201112_1510.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/migrations/0003_auto_20201113_2133.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/migrations/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/models.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/tests.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/urls.py
  students/14th/team_05/seungchan-baek/project_westagram/follow/views.py
  students/14th/team_05/seungchan-baek/project_westagram/manage.py
  students/14th/team_05/seungchan-baek/project_westagram/post/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/post/admin.py
  students/14th/team_05/seungchan-baek/project_westagram/post/apps.py
  students/14th/team_05/seungchan-baek/project_westagram/post/migrations/0001_initial.py
  students/14th/team_05/seungchan-baek/project_westagram/post/migrations/0002_comment.py
  students/14th/team_05/seungchan-baek/project_westagram/post/migrations/0003_auto_20201110_2337.py
  students/14th/team_05/seungchan-baek/project_westagram/post/migrations/0004_auto_20201113_0019.py
  students/14th/team_05/seungchan-baek/project_westagram/post/migrations/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/post/models.py
  students/14th/team_05/seungchan-baek/project_westagram/post/tests.py
  students/14th/team_05/seungchan-baek/project_westagram/post/urls.py
  students/14th/team_05/seungchan-baek/project_westagram/post/views.py
  students/14th/team_05/seungchan-baek/project_westagram/project_westagram/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/project_westagram/settings.py
  students/14th/team_05/seungchan-baek/project_westagram/project_westagram/urls.py
  students/14th/team_05/seungchan-baek/project_westagram/project_westagram/wsgi.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/admin.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/apps.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/migrations/0001_initial.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/migrations/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/models.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/tests.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/urls.py
  students/14th/team_05/seungchan-baek/project_westagram/thumbs_up/views.py
  students/14th/team_05/seungchan-baek/project_westagram/user/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/user/admin.py
  students/14th/team_05/seungchan-baek/project_westagram/user/apps.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0001_initial.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0002_auto_20201104_1613.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0003_auto_20201105_0427.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0004_auto_20201106_1846.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0005_auto_20201110_2337.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0006_auto_20201111_0106.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0007_auto_20201111_0108.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0008_auto_20201111_1602.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/0009_auto_20201111_1610.py
  students/14th/team_05/seungchan-baek/project_westagram/user/migrations/__init__.py
  students/14th/team_05/seungchan-baek/project_westagram/user/models.py
  students/14th/team_05/seungchan-baek/project_westagram/user/urls.py
  students/14th/team_05/seungchan-baek/project_westagram/user/utils.py
  students/14th/team_05/seungchan-baek/project_westagram/user/views.py
  students/14th/team_05/seungchan-baek/project_westagram/westa/*.csv
  students/14th/team_05/seungchan-baek/project_westagram/westa/.gitignore
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#113 김민서 | Add: 비번 암호화 후 회원가입, 로그인 토큰 발행 구현
  students/14th/team8/minseo-kim/project_westagram/manage.py
  students/14th/team8/minseo-kim/project_westagram/posting/\
  students/14th/team8/minseo-kim/project_westagram/posting/__init__.py
  students/14th/team8/minseo-kim/project_westagram/posting/admin.py
  students/14th/team8/minseo-kim/project_westagram/posting/apps.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0001_initial.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0002_auto_20201108_1458.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0003_auto_20201108_1655.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0004_auto_20201109_1138.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0005_auto_20201109_1705.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0006_auto_20201110_2142.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0007_auto_20201110_2146.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0008_comment.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/0009_auto_20201110_2219.py
  students/14th/team8/minseo-kim/project_westagram/posting/migrations/__init__.py
  students/14th/team8/minseo-kim/project_westagram/posting/models.py
  students/14th/team8/minseo-kim/project_westagram/posting/tests.py
  students/14th/team8/minseo-kim/project_westagram/posting/urls.py
  students/14th/team8/minseo-kim/project_westagram/posting/views.py
  students/14th/team8/minseo-kim/project_westagram/project_westagram/__init__.py
  students/14th/team8/minseo-kim/project_westagram/project_westagram/asgi.py
  students/14th/team8/minseo-kim/project_westagram/project_westagram/settings.py
  students/14th/team8/minseo-kim/project_westagram/project_westagram/urls.py
  students/14th/team8/minseo-kim/project_westagram/project_westagram/wsgi.py
  students/14th/team8/minseo-kim/project_westagram/user/__init__.py
  students/14th/team8/minseo-kim/project_westagram/user/admin.py
  students/14th/team8/minseo-kim/project_westagram/user/apps.py
  students/14th/team8/minseo-kim/project_westagram/user/migrations/0001_initial.py
  students/14th/team8/minseo-kim/project_westagram/user/migrations/0002_auto_20201106_0746.py
  students/14th/team8/minseo-kim/project_westagram/user/migrations/0003_auto_20201108_1458.py
  students/14th/team8/minseo-kim/project_westagram/user/migrations/0004_auto_20201109_1705.py
  students/14th/team8/minseo-kim/project_westagram/user/migrations/0005_auto_20201110_1358.py
  students/14th/team8/minseo-kim/project_westagram/user/migrations/__init__.py
  students/14th/team8/minseo-kim/project_westagram/user/models.py
  students/14th/team8/minseo-kim/project_westagram/user/tests.py
  students/14th/team8/minseo-kim/project_westagram/user/urls.py
  students/14th/team8/minseo-kim/project_westagram/user/views.py
Labels: Status : 수정 요청

#119 [14th 고수희] #4 게시물 등록 및 #5 댓글 등록/표출 구현, 인증/인가 구현 및 수정 사항 반영
  students/14th/team_05/suhee-go/project_westagram/.gitignore
  students/14th/team_05/suhee-go/project_westagram/manage.py
  students/14th/team_05/suhee-go/project_westagram/posting/__init__.py
  students/14th/team_05/suhee-go/project_westagram/posting/admin.py
  students/14th/team_05/suhee-go/project_westagram/posting/apps.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0001_initial.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0002_auto_20201110_1543.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0003_auto_20201110_1734.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0004_remove_post_updated_at.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0005_auto_20201110_2251.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0006_comment.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/0007_auto_20201115_0152.py
  students/14th/team_05/suhee-go/project_westagram/posting/migrations/__init__.py
  students/14th/team_05/suhee-go/project_westagram/posting/models.py
  students/14th/team_05/suhee-go/project_westagram/posting/tests.py
  students/14th/team_05/suhee-go/project_westagram/posting/urls.py
  students/14th/team_05/suhee-go/project_westagram/posting/views.py
  students/14th/team_05/suhee-go/project_westagram/project_westagram/__init__.py
  students/14th/team_05/suhee-go/project_westagram/project_westagram/asgi.py
  students/14th/team_05/suhee-go/project_westagram/project_westagram/settings.py
  students/14th/team_05/suhee-go/project_westagram/project_westagram/urls.py
  students/14th/team_05/suhee-go/project_westagram/project_westagram/wsgi.py
  students/14th/team_05/suhee-go/project_westagram/requirements.txt
  students/14th/team_05/suhee-go/project_westagram/user/@
  students/14th/team_05/suhee-go/project_westagram/user/__init__.py
  students/14th/team_05/suhee-go/project_westagram/user/admin.py
  students/14th/team_05/suhee-go/project_westagram/user/apps.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0001_initial.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0002_auto_20201105_1749.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0003_auto_20201105_1926.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0004_auto_20201105_1928.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0005_auto_20201105_1929.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0006_auto_20201105_1939.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0007_auto_20201105_1949.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0008_auto_20201106_1604.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/0009_auto_20201109_1640.py
  students/14th/team_05/suhee-go/project_westagram/user/migrations/__init__.py
  students/14th/team_05/suhee-go/project_westagram/user/models.py
  students/14th/team_05/suhee-go/project_westagram/user/tests.py
  students/14th/team_05/suhee-go/project_westagram/user/urls.py
  students/14th/team_05/suhee-go/project_westagram/user/utils.py
  students/14th/team_05/suhee-go/project_westagram/user/views.py
Labels: Status : 리뷰 요청, 추가 구현 사항, 필수 구현 사항

#120 [14기 김영환] mission 1,2,3,4,5 구현
  posting/__init__.py
  posting/admin.py
  posting/apps.py
  posting/migrations/0001_initial.py
  posting/migrations/0002_auto_20201107_1620.py
  posting/migrations/0003_auto_20201108_1248.py
  posting/migrations/0004_auto_20201109_0458.py
  posting/migrations/__init__.py
  posting/models.py
  posting/tests.py
  posting/urls.py
  posting/views.py
  project_westagram/__init__.py
  project_westagram/asgi.py
  project_westagram/settings.py
  project_westagram/urls.py
  project_westagram/wsgi.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201105_0449.py
  user/migrations/0003_auto_20201105_0511.py
  user/migrations/0004_auto_20201105_1045.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status : 수정 요청

#122 14기 정현석 게시판 구현
  students/14th/team_6/hyun/project_westagram/.vscode/settings.json
  students/14th/team_6/hyun/project_westagram/.vscode/tset.py
  students/14th/team_6/hyun/project_westagram/manage.py
  students/14th/team_6/hyun/project_westagram/posting/__init__.py
  students/14th/team_6/hyun/project_westagram/posting/admin.py
  students/14th/team_6/hyun/project_westagram/posting/apps.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/0001_initial.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/0002_auto_20201108_2256.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/0003_auto_20201109_1251.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/0004_auto_20201109_1630.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/0005_post_photo.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/0006_auto_20201109_1653.py
  students/14th/team_6/hyun/project_westagram/posting/migrations/__init__.py
  students/14th/team_6/hyun/project_westagram/posting/models.py
  students/14th/team_6/hyun/project_westagram/posting/tests.py
  students/14th/team_6/hyun/project_westagram/posting/urls.py
  students/14th/team_6/hyun/project_westagram/posting/views.py
  students/14th/team_6/hyun/project_westagram/project_westagram/__init__.py
  students/14th/team_6/hyun/project_westagram/project_westagram/asgi.py
  students/14th/team_6/hyun/project_westagram/project_westagram/settings.py
  students/14th/team_6/hyun/project_westagram/project_westagram/urls.py
  students/14th/team_6/hyun/project_westagram/project_westagram/wsgi.py
  students/14th/team_6/hyun/project_westagram/user/.vscode/settings.json
  students/14th/team_6/hyun/project_westagram/user/__init__.py
  students/14th/team_6/hyun/project_westagram/user/admin.py
  students/14th/team_6/hyun/project_westagram/user/apps.py
  students/14th/team_6/hyun/project_westagram/user/migrations/0001_initial.py
  students/14th/team_6/hyun/project_westagram/user/migrations/0002_auto_20201109_2234.py
  students/14th/team_6/hyun/project_westagram/user/migrations/__init__.py
  students/14th/team_6/hyun/project_westagram/user/models.py
  students/14th/team_6/hyun/project_westagram/user/tests.py
  students/14th/team_6/hyun/project_westagram/user/urls.py
  students/14th/team_6/hyun/project_westagram/user/views.py
Labels: Status : 수정 요청

#123 [14기 김민구] 대댓글 구현
  students/14th/team8/minkoo/.gitignore
  students/14th/team8/minkoo/.idea/.gitignore
  students/14th/team8/minkoo/.idea/inspectionProfiles/profiles_settings.xml
  students/14th/team8/minkoo/.idea/minkoo.iml
  students/14th/team8/minkoo/.idea/misc.xml
  students/14th/team8/minkoo/.idea/modules.xml
  students/14th/team8/minkoo/.idea/vcs.xml
  students/14th/team8/minkoo/project_westagram/manage.py
  students/14th/team8/minkoo/project_westagram/posting/__init__.py
  students/14th/team8/minkoo/project_westagram/posting/admin.py
  students/14th/team8/minkoo/project_westagram/posting/apps.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0001_initial.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0002_auto_20201106_1515.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0003_comment.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0004_like.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0005_reply.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0006_auto_20201109_1900.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/0007_auto_20201109_1901.py
  students/14th/team8/minkoo/project_westagram/posting/migrations/__init__.py
  students/14th/team8/minkoo/project_westagram/posting/models.py
  students/14th/team8/minkoo/project_westagram/posting/tests.py
  students/14th/team8/minkoo/project_westagram/posting/urls.py
  students/14th/team8/minkoo/project_westagram/posting/views.py
  students/14th/team8/minkoo/project_westagram/project_westagram/__init__.py
  students/14th/team8/minkoo/project_westagram/project_westagram/asgi.py
  students/14th/team8/minkoo/project_westagram/project_westagram/settings/settings.py
  students/14th/team8/minkoo/project_westagram/project_westagram/urls.py
  students/14th/team8/minkoo/project_westagram/project_westagram/wsgi.py
  students/14th/team8/minkoo/project_westagram/pytest.ini
  students/14th/team8/minkoo/project_westagram/user/__init__.py
  students/14th/team8/minkoo/project_westagram/user/admin.py
  students/14th/team8/minkoo/project_westagram/user/apps.py
  students/14th/team8/minkoo/project_westagram/user/migrations/0001_initial.py
  students/14th/team8/minkoo/project_westagram/user/migrations/0002_auto_20201106_1346.py
  students/14th/team8/minkoo/project_westagram/user/migrations/0003_followlist.py
  students/14th/team8/minkoo/project_westagram/user/migrations/0004_auto_20201108_2335.py
  students/14th/team8/minkoo/project_westagram/user/migrations/0005_auto_20201109_1900.py
  students/14th/team8/minkoo/project_westagram/user/migrations/__init__.py
  students/14th/team8/minkoo/project_westagram/user/models.py
  students/14th/team8/minkoo/project_westagram/user/tests.py
  students/14th/team8/minkoo/project_westagram/user/urls.py
  students/14th/team8/minkoo/project_westagram/user/views.py
  students/14th/team8/minkoo/requirements/requirements.txt
Labels: Status : 수정 요청, 추가 구현 사항, 필수 구현 사항
