Repository wecode-bootcamp-korea/westagram-backend, pull requests merged in 2020-12, with the labels that each got.

#136 [오승현] initial settings 에 관한 PR 입니다
  students/15th/teamteam/seunghyun/.gitignore
  students/15th/teamteam/seunghyun/manage.py
  students/15th/teamteam/seunghyun/requirements.txt
  students/15th/teamteam/seunghyun/westagram/__init__.py
  students/15th/teamteam/seunghyun/westagram/asgi.py
  students/15th/teamteam/seunghyun/westagram/settings.py
  students/15th/teamteam/seunghyun/westagram/urls.py
  students/15th/teamteam/seunghyun/westagram/wsgi.py
Labels: Status : 리뷰 요청

#134 [김원희] Add: 초기 설정 완료
  students/15th/team1/wonhee_kim/.gitignore
  students/15th/team1/wonhee_kim/manage.py
  students/15th/team1/wonhee_kim/my_settins.py
  students/15th/team1/wonhee_kim/requirement.txt
  students/15th/team1/wonhee_kim/westargram/__init__.py
  students/15th/team1/wonhee_kim/westargram/asgi.py
  students/15th/team1/wonhee_kim/westargram/settings.py
  students/15th/team1/wonhee_kim/westargram/urls.py
  students/15th/team1/wonhee_kim/westargram/wsgi.py
Labels: Status : 리뷰 요청

#128 [이주형] Add: sign-in completed
  students/15th/team3/juhyung_lee/.gitignore
  students/15th/team3/juhyung_lee/manage.py
  students/15th/team3/juhyung_lee/requirements.txt
  students/15th/team3/juhyung_lee/users/__init__.py
  students/15th/team3/juhyung_lee/users/admin.py
  students/15th/team3/juhyung_lee/users/apps.py
  students/15th/team3/juhyung_lee/users/migrations/0001_initial.py
  students/15th/team3/juhyung_lee/users/migrations/0002_auto_20201203_0819.py
  students/15th/team3/juhyung_lee/users/migrations/0003_auto_20201204_0053.py
  students/15th/team3/juhyung_lee/users/migrations/0004_auto_20201204_1007.py
  students/15th/team3/juhyung_lee/users/migrations/0005_auto_20201204_1029.py
  students/15th/team3/juhyung_lee/users/migrations/0006_auto_20201204_1045.py
  students/15th/team3/juhyung_lee/users/migrations/0007_auto_20201204_1052.py
  students/15th/team3/juhyung_lee/users/migrations/0008_auto_20201204_1506.py
  students/15th/team3/juhyung_lee/users/migrations/0009_auto_20201204_1508.py
  students/15th/team3/juhyung_lee/users/migrations/0010_auto_20201208_0709.py
  students/15th/team3/juhyung_lee/users/migrations/0011_auto_20201209_0717.py
  students/15th/team3/juhyung_lee/users/migrations/__init__.py
  students/15th/team3/juhyung_lee/users/models.py
  students/15th/team3/juhyung_lee/users/tests.py
  students/15th/team3/juhyung_lee/users/urls.py
  students/15th/team3/juhyung_lee/users/views.py
  students/15th/team3/juhyung_lee/westagram/__init__.py
  students/15th/team3/juhyung_lee/westagram/asgi.py
  students/15th/team3/juhyung_lee/westagram/settings.py
  students/15th/team3/juhyung_lee/westagram/urls.py
  students/15th/team3/juhyung_lee/westagram/wsgi.py
Labels: Status : 수정 요청

#129 [우혁준] Add: initial settings complete
  students/15th/team1/hwukjunwoo/.gitignore
  students/15th/team1/hwukjunwoo/manage.py
  students/15th/team1/hwukjunwoo/requirements.txt
  students/15th/team1/hwukjunwoo/user/__init__.py
  students/15th/team1/hwukjunwoo/user/admin.py
  students/15th/team1/hwukjunwoo/user/apps.py
  students/15th/team1/hwukjunwoo/user/migrations/0001_initial.py
  students/15th/team1/hwukjunwoo/user/migrations/0002_auto_20201208_0802.py
  students/15th/team1/hwukjunwoo/user/migrations/0003_auto_20201208_1418.py
  students/15th/team1/hwukjunwoo/user/migrations/0004_auto_20201209_1533.py
  students/15th/team1/hwukjunwoo/user/migrations/0005_auto_20201210_0129.py
  students/15th/team1/hwukjunwoo/user/migrations/0006_auto_20201211_0057.py
  students/15th/team1/hwukjunwoo/user/migrations/__init__.py
  students/15th/team1/hwukjunwoo/user/models.py
  students/15th/team1/hwukjunwoo/user/tests.py
  students/15th/team1/hwukjunwoo/user/urls.py
  students/15th/team1/hwukjunwoo/user/views.py
  students/15th/team1/hwukjunwoo/westagram/__init__.py
  students/15th/team1/hwukjunwoo/westagram/asgi.py
  students/15th/team1/hwukjunwoo/westagram/settings.py
  students/15th/team1/hwukjunwoo/westagram/urls.py
  students/15th/team1/hwukjunwoo/westagram/views.py
  students/15th/team1/hwukjunwoo/westagram/wsgi.py
Labels: Status : 수정 요청

#130 [이재혁] Add: westagram 좋아요 기능 구현
  students/15th/team4/jaehyeok_lee/.gitignore
  students/15th/team4/jaehyeok_lee/follow/__init__.py
  students/15th/team4/jaehyeok_lee/follow/admin.py
  students/15th/team4/jaehyeok_lee/follow/apps.py
  students/15th/team4/jaehyeok_lee/follow/migrations/__init__.py
  students/15th/team4/jaehyeok_lee/follow/models.py
  students/15th/team4/jaehyeok_lee/follow/tests.py
  students/15th/team4/jaehyeok_lee/follow/views.py
  students/15th/team4/jaehyeok_lee/like/__init__.py
  students/15th/team4/jaehyeok_lee/like/admin.py
  students/15th/team4/jaehyeok_lee/like/apps.py
  students/15th/team4/jaehyeok_lee/like/migrations/0001_initial.py
  students/15th/team4/jaehyeok_lee/like/migrations/__init__.py
  students/15th/team4/jaehyeok_lee/like/models.py
  students/15th/team4/jaehyeok_lee/like/tests.py
  students/15th/team4/jaehyeok_lee/like/urls.py
  students/15th/team4/jaehyeok_lee/like/views.py
  students/15th/team4/jaehyeok_lee/manage.py
  students/15th/team4/jaehyeok_lee/post/__init__.py
  students/15th/team4/jaehyeok_lee/post/admin.py
  students/15th/team4/jaehyeok_lee/post/apps.py
  students/15th/team4/jaehyeok_lee/post/migrations/0001_initial.py
  students/15th/team4/jaehyeok_lee/post/migrations/0002_auto_20201205_1213.py
  students/15th/team4/jaehyeok_lee/post/migrations/__init__.py
  students/15th/team4/jaehyeok_lee/post/models.py
  students/15th/team4/jaehyeok_lee/post/tests.py
  students/15th/team4/jaehyeok_lee/post/urls.py
  students/15th/team4/jaehyeok_lee/post/views.py
  students/15th/team4/jaehyeok_lee/requirements.txt
  students/15th/team4/jaehyeok_lee/user/__init__.py
  students/15th/team4/jaehyeok_lee/user/admin.py
  students/15th/team4/jaehyeok_lee/user/apps.py
  students/15th/team4/jaehyeok_lee/user/migrations/0001_initial.py
  students/15th/team4/jaehyeok_lee/user/migrations/0002_auto_20201203_0720.py
  students/15th/team4/jaehyeok_lee/user/migrations/0003_auto_20201203_0721.py
  students/15th/team4/jaehyeok_lee/user/migrations/0004_auto_20201208_0116.py
  students/15th/team4/jaehyeok_lee/user/migrations/__init__.py
  students/15th/team4/jaehyeok_lee/user/models.py
  students/15th/team4/jaehyeok_lee/user/tests.py
  students/15th/team4/jaehyeok_lee/user/urls.py
  students/15th/team4/jaehyeok_lee/user/utils.py
  students/15th/team4/jaehyeok_lee/user/views.py
  students/15th/team4/jaehyeok_lee/westagram/__init__.py
  students/15th/team4/jaehyeok_lee/westagram/asgi.py
  students/15th/team4/jaehyeok_lee/westagram/settings.py
  students/15th/team4/jaehyeok_lee/westagram/urls.py
  students/15th/team4/jaehyeok_lee/westagram/wsgi.py
Labels: Status : 리뷰 요청

#131 [김민철] Add: mission3 , 토큰 , 코드리뷰 반영해서 수정 완료
  students/15th/team3/.gitignore
  students/15th/team3/manage.py
  students/15th/team3/requirements.txt
  students/15th/team3/user/__init__.py
  students/15th/team3/user/admin.py
  students/15th/team3/user/apps.py
  students/15th/team3/user/migrations/0001_initial.py
  students/15th/team3/user/migrations/0002_auto_20201206_2035.py
  students/15th/team3/user/migrations/0003_remove_signup_user_id.py
  students/15th/team3/user/migrations/0004_auto_20201206_2153.py
  students/15th/team3/user/migrations/0005_auto_20201207_0642.py
  students/15th/team3/user/migrations/__init__.py
  students/15th/team3/user/models.py
  students/15th/team3/user/tests.py
  students/15th/team3/user/urls.py
  students/15th/team3/user/views.py
  students/15th/team3/westagram/__init__.py
  students/15th/team3/westagram/asgi.py
  students/15th/team3/westagram/settings.py
  students/15th/team3/westagram/urls.py
  students/15th/team3/westagram/wsgi.py
Labels: Status : 리뷰 요청

#132 [문승희] 댓글 추가 기능 구현 완료
  students/15th/team2/seunghee_mun/.gitignore
  students/15th/team2/seunghee_mun/board/__init__.py
  students/15th/team2/seunghee_mun/board/admin.py
  students/15th/team2/seunghee_mun/board/apps.py
  students/15th/team2/seunghee_mun/board/migrations/0001_initial.py
  students/15th/team2/seunghee_mun/board/migrations/__init__.py
  students/15th/team2/seunghee_mun/board/models.py
  students/15th/team2/seunghee_mun/board/urls.py
  students/15th/team2/seunghee_mun/board/views.py
  students/15th/team2/seunghee_mun/manage.py
  students/15th/team2/seunghee_mun/requirements.txt
  students/15th/team2/seunghee_mun/user/__init__.py
  students/15th/team2/seunghee_mun/user/admin.py
  students/15th/team2/seunghee_mun/user/apps.py
  students/15th/team2/seunghee_mun/user/migrations/0001_initial.py
  students/15th/team2/seunghee_mun/user/migrations/0002_auto_20201208_2103.py
  students/15th/team2/seunghee_mun/user/migrations/__init__.py
  students/15th/team2/seunghee_mun/user/models.py
  students/15th/team2/seunghee_mun/user/urls.py
  students/15th/team2/seunghee_mun/user/utils.py
  students/15th/team2/seunghee_mun/user/views.py
  students/15th/team2/seunghee_mun/westagram/__init__.py
  students/15th/team2/seunghee_mun/westagram/asgi.py
  students/15th/team2/seunghee_mun/westagram/settings.py
  students/15th/team2/seunghee_mun/westagram/urls.py
  students/15th/team2/seunghee_mun/westagram/wsgi.py
Labels: Status : 리뷰 요청

#133 [김순태] Login End-point Completed
  students/15th/team1/suntae_kim/.gitignore
  students/15th/team1/suntae_kim/manage.py
  students/15th/team1/suntae_kim/posting/__init__.py
  students/15th/team1/suntae_kim/posting/admin.py
  students/15th/team1/suntae_kim/posting/apps.py
  students/15th/team1/suntae_kim/posting/migrations/0001_initial.py
  students/15th/team1/suntae_kim/posting/migrations/0002_boardcomment_posting.py
  students/15th/team1/suntae_kim/posting/migrations/0003_auto_20201210_1751.py
  students/15th/team1/suntae_kim/posting/migrations/__init__.py
  students/15th/team1/suntae_kim/posting/models.py
  students/15th/team1/suntae_kim/posting/tests.py
  students/15th/team1/suntae_kim/posting/urls.py
  students/15th/team1/suntae_kim/posting/views.py
  students/15th/team1/suntae_kim/requirements.txt
  students/15th/team1/suntae_kim/user/__init__.py
  students/15th/team1/suntae_kim/user/admin.py
  students/15th/team1/suntae_kim/user/apps.py
  students/15th/team1/suntae_kim/user/migrations/0001_initial.py
  students/15th/team1/suntae_kim/user/migrations/0002_auto_20201208_1543.py
  students/15th/team1/suntae_kim/user/migrations/__init__.py
  students/15th/team1/suntae_kim/user/models.py
  students/15th/team1/suntae_kim/user/tests.py
  students/15th/team1/suntae_kim/user/urls.py
  students/15th/team1/suntae_kim/user/utils.py
  students/15th/team1/suntae_kim/user/views.py
  students/15th/team1/suntae_kim/westagram/__init__.py
  students/15th/team1/suntae_kim/westagram/asgi.py
  students/15th/team1/suntae_kim/westagram/settings.py
  students/15th/team1/suntae_kim/westagram/urls.py
  students/15th/team1/suntae_kim/westagram/wsgi.py
Labels: Status : 리뷰 진행중

#137 [15기-이수한] ADD: inital settings complete
  students/15th/turtle/suhan/westagram/manage.py
  students/15th/turtle/suhan/westagram/posting/__init__.py
  students/15th/turtle/suhan/westagram/posting/admin.py
  students/15th/turtle/suhan/westagram/posting/apps.py
  students/15th/turtle/suhan/westagram/posting/migrations/__init__.py
  students/15th/turtle/suhan/westagram/posting/models.py
  students/15th/turtle/suhan/westagram/posting/tests.py
  students/15th/turtle/suhan/westagram/posting/views.py
  students/15th/turtle/suhan/westagram/user/__init__.py
  students/15th/turtle/suhan/westagram/user/admin.py
  students/15th/turtle/suhan/westagram/user/apps.py
  students/15th/turtle/suhan/westagram/user/migrations/0001_initial.py
  students/15th/turtle/suhan/westagram/user/migrations/__init__.py
  students/15th/turtle/suhan/westagram/user/models.py
  students/15th/turtle/suhan/westagram/user/tests.py
  students/15th/turtle/suhan/westagram/user/urls.py
  students/15th/turtle/suhan/westagram/user/views.py
  students/15th/turtle/suhan/westagram/westagram/.gitignore
  students/15th/turtle/suhan/westagram/westagram/__init__.py
  students/15th/turtle/suhan/westagram/westagram/asgi.py
  students/15th/turtle/suhan/westagram/westagram/requirememts.txt
  students/15th/turtle/suhan/westagram/westagram/settings.py
  students/15th/turtle/suhan/westagram/westagram/urls.py
  students/15th/turtle/suhan/westagram/westagram/wsgi.py
Labels: Status : 수정 요청

#139 [이승연] Add: initial settings complete
  students/15th/team1/seungyun-lee/.gitignore
  students/15th/team1/seungyun-lee/manage.py
  students/15th/team1/seungyun-lee/requirements.txt
  students/15th/team1/seungyun-lee/user/__init__.py
  students/15th/team1/seungyun-lee/user/admin.py
  students/15th/team1/seungyun-lee/user/apps.py
  students/15th/team1/seungyun-lee/user/migrations/0001_initial.py
  students/15th/team1/seungyun-lee/user/migrations/0002_auto_20201207_1043.py
  students/15th/team1/seungyun-lee/user/migrations/0003_auto_20201209_0717.py
  students/15th/team1/seungyun-lee/user/migrations/0004_auto_20201214_1001.py
  students/15th/team1/seungyun-lee/user/migrations/__init__.py
  students/15th/team1/seungyun-lee/user/models.py
  students/15th/team1/seungyun-lee/user/tests.py
  students/15th/team1/seungyun-lee/user/urls.py
  students/15th/team1/seungyun-lee/user/views.py
  students/15th/team1/seungyun-lee/westagram/__init__.py
  students/15th/team1/seungyun-lee/westagram/asgi.py
  students/15th/team1/seungyun-lee/westagram/requirements.txt
  students/15th/team1/seungyun-lee/westagram/settings.py
  students/15th/team1/seungyun-lee/westagram/urls.py
  students/15th/team1/seungyun-lee/westagram/utils.py
  students/15th/team1/seungyun-lee/westagram/wsgi.py
Labels: Status : 수정 요청

#140 [유하람] Add: initial settings complete
  students/15th/team3/hailee/westagram/.gitignore
  students/15th/team3/hailee/westagram/manage.py
  students/15th/team3/hailee/westagram/requirements.txt
  students/15th/team3/hailee/westagram/user/__init__.py
  students/15th/team3/hailee/westagram/user/admin.py
  students/15th/team3/hailee/westagram/user/apps.py
  students/15th/team3/hailee/westagram/user/migrations/0001_initial.py
  students/15th/team3/hailee/westagram/user/migrations/0002_auto_20201208_0531.py
  students/15th/team3/hailee/westagram/user/migrations/0003_users_id_type.py
  students/15th/team3/hailee/westagram/user/migrations/0004_auto_20201208_0644.py
  students/15th/team3/hailee/westagram/user/migrations/0005_auto_20201208_0702.py
  students/15th/team3/hailee/westagram/user/migrations/0006_auto_20201208_0705.py
  students/15th/team3/hailee/westagram/user/migrations/0007_auto_20201208_0706.py
  students/15th/team3/hailee/westagram/user/migrations/0008_delete_user.py
  students/15th/team3/hailee/westagram/user/migrations/0009_user.py
  students/15th/team3/hailee/westagram/user/migrations/0010_auto_20201208_1431.py
  students/15th/team3/hailee/westagram/user/migrations/0011_auto_20201210_0854.py
  students/15th/team3/hailee/westagram/user/migrations/0012_auto_20201211_1822.py
  students/15th/team3/hailee/westagram/user/migrations/__init__.py
  students/15th/team3/hailee/westagram/user/models.py
  students/15th/team3/hailee/westagram/user/tests.py
  students/15th/team3/hailee/westagram/user/urls.py
  students/15th/team3/hailee/westagram/user/views.py
  students/15th/team3/hailee/westagram/westagram/__init__.py
  students/15th/team3/hailee/westagram/westagram/asgi.py
  students/15th/team3/hailee/westagram/westagram/settings.py
  students/15th/team3/hailee/westagram/westagram/urls.py
  students/15th/team3/hailee/westagram/westagram/wsgi.py
Labels: Status : 수정 요청

#141 [김기수] Add: Password 암호화, 로그인 / 엑세스 토큰 발행 구현
  students/15th/team1/gisu-kim/.gitignore
  students/15th/team1/gisu-kim/manage.py
  students/15th/team1/gisu-kim/requirements.txt
  students/15th/team1/gisu-kim/user/__init__.py
  students/15th/team1/gisu-kim/user/admin.py
  students/15th/team1/gisu-kim/user/apps.py
  students/15th/team1/gisu-kim/user/migrations/0001_initial.py
  students/15th/team1/gisu-kim/user/migrations/0002_auto_20201210_0521.py
  students/15th/team1/gisu-kim/user/migrations/0003_auto_20201211_0024.py
  students/15th/team1/gisu-kim/user/migrations/0004_auto_20201213_1421.py
  students/15th/team1/gisu-kim/user/migrations/0005_auto_20201213_1421.py
  students/15th/team1/gisu-kim/user/migrations/__init__.py
  students/15th/team1/gisu-kim/user/models.py
  students/15th/team1/gisu-kim/user/tests.py
  students/15th/team1/gisu-kim/user/urls.py
  students/15th/team1/gisu-kim/user/views.py
  students/15th/team1/gisu-kim/westagram/__init__.py
  students/15th/team1/gisu-kim/westagram/asgi.py
  students/15th/team1/gisu-kim/westagram/settings.py
  students/15th/team1/gisu-kim/westagram/urls.py
  students/15th/team1/gisu-kim/westagram/wsgi.py
Labels: Status : 수정 요청

#143 [김한별] 회원가입/로그인 앤드포인트 구현
  students/15th/turtle/hanbyul-kim/.gitignore
  students/15th/turtle/hanbyul-kim/manage.py
  students/15th/turtle/hanbyul-kim/requirements.txt
  students/15th/turtle/hanbyul-kim/user/__init__.py
  students/15th/turtle/hanbyul-kim/user/admin.py
  students/15th/turtle/hanbyul-kim/user/apps.py
  students/15th/turtle/hanbyul-kim/user/migrations/0001_initial.py
  students/15th/turtle/hanbyul-kim/user/migrations/0002_auto_20201209_0321.py
  students/15th/turtle/hanbyul-kim/user/migrations/__init__.py
  students/15th/turtle/hanbyul-kim/user/models.py
  students/15th/turtle/hanbyul-kim/user/tests.py
  students/15th/turtle/hanbyul-kim/user/urls.py
  students/15th/turtle/hanbyul-kim/user/views.py
  students/15th/turtle/hanbyul-kim/westargram/__init__.py
  students/15th/turtle/hanbyul-kim/westargram/asgi.py
  students/15th/turtle/hanbyul-kim/westargram/settings.py
  students/15th/turtle/hanbyul-kim/westargram/urls.py
  students/15th/turtle/hanbyul-kim/westargram/wsgi.py
Labels: Status : 수정 요청

#145 [석여주]암호화토큰 발급완료(수정)
  students/15th/team3/yeoju-seok/.gitignore
  students/15th/team3/yeoju-seok/manage.py
  students/15th/team3/yeoju-seok/requirements.txt
  students/15th/team3/yeoju-seok/user/__init__.py
  students/15th/team3/yeoju-seok/user/admin.py
  students/15th/team3/yeoju-seok/user/apps.py
  students/15th/team3/yeoju-seok/user/migrations/0001_initial.py
  students/15th/team3/yeoju-seok/user/migrations/0002_auto_20201212_0813.py
  students/15th/team3/yeoju-seok/user/migrations/0003_auto_20201212_1132.py
  students/15th/team3/yeoju-seok/user/migrations/__init__.py
  students/15th/team3/yeoju-seok/user/models.py
  students/15th/team3/yeoju-seok/user/tests.py
  students/15th/team3/yeoju-seok/user/urls.py
  students/15th/team3/yeoju-seok/user/views.py
  students/15th/team3/yeoju-seok/westagram/__init__.py
  students/15th/team3/yeoju-seok/westagram/asgi.py
  students/15th/team3/yeoju-seok/westagram/settings.py
  students/15th/team3/yeoju-seok/westagram/urls.py
  students/15th/team3/yeoju-seok/westagram/wsgi.py
Labels: Status : 리뷰 요청

#158 [이현주] 로그인 기능 구현(암호화 & 토큰 완료)
  students/15th/teamteam/hyeonju/.gitignore
  students/15th/teamteam/hyeonju/manage.py
  students/15th/teamteam/hyeonju/requirements.txt
  students/15th/teamteam/hyeonju/westagram/.gitignore
  students/15th/teamteam/hyeonju/westagram/manage.py
  students/15th/teamteam/hyeonju/westagram/user/__init__.py
  students/15th/teamteam/hyeonju/westagram/user/admin.py
  students/15th/teamteam/hyeonju/westagram/user/apps.py
  students/15th/teamteam/hyeonju/westagram/user/migrations/0001_initial.py
  students/15th/teamteam/hyeonju/westagram/user/migrations/0002_auto_20201209_0821.py
  students/15th/teamteam/hyeonju/westagram/user/migrations/0003_auto_20201209_0833.py
  students/15th/teamteam/hyeonju/westagram/user/migrations/0004_signin.py
  students/15th/teamteam/hyeonju/westagram/user/migrations/0005_auto_20201209_1451.py
  students/15th/teamteam/hyeonju/westagram/user/migrations/__init__.py
  students/15th/teamteam/hyeonju/westagram/user/models.py
  students/15th/teamteam/hyeonju/westagram/user/tests.py
  students/15th/teamteam/hyeonju/westagram/user/urls.py
  students/15th/teamteam/hyeonju/westagram/user/views.py
  students/15th/teamteam/hyeonju/westagram/westagram/__init__.py
  students/15th/teamteam/hyeonju/westagram/westagram/asgi.py
  students/15th/teamteam/hyeonju/westagram/westagram/settings.py
  students/15th/teamteam/hyeonju/westagram/westagram/urls.py
  students/15th/teamteam/hyeonju/westagram/westagram/wsgi.py
Labels: Status : 수정 요청

#160 [김원희] ADD: [Mission 8] 게시물 및 댓글 삭제 기능 구현 완료
  students/15th/team1/wonhee_kim/my_settins.py
  students/15th/team1/wonhee_kim/post/__init__.py
  students/15th/team1/wonhee_kim/post/admin.py
  students/15th/team1/wonhee_kim/post/apps.py
  students/15th/team1/wonhee_kim/post/migrations/0001_initial.py
  students/15th/team1/wonhee_kim/post/migrations/0002_auto_20201208_1539.py
  students/15th/team1/wonhee_kim/post/migrations/0003_comment.py
  students/15th/team1/wonhee_kim/post/migrations/0004_post_liker.py
  students/15th/team1/wonhee_kim/post/migrations/0005_auto_20201210_2013.py
  students/15th/team1/wonhee_kim/post/migrations/0006_auto_20201210_2024.py
  students/15th/team1/wonhee_kim/post/migrations/__init__.py
  students/15th/team1/wonhee_kim/post/models.py
  students/15th/team1/wonhee_kim/post/tests.py
  students/15th/team1/wonhee_kim/post/urls.py
  students/15th/team1/wonhee_kim/post/views/comment_views.py
  students/15th/team1/wonhee_kim/post/views/like_views.py
  students/15th/team1/wonhee_kim/post/views/post_views.py
  students/15th/team1/wonhee_kim/user/__init__.py
  students/15th/team1/wonhee_kim/user/admin.py
  students/15th/team1/wonhee_kim/user/apps.py
  students/15th/team1/wonhee_kim/user/migrations/0001_initial.py
  students/15th/team1/wonhee_kim/user/migrations/0002_auto_20201208_0905.py
  students/15th/team1/wonhee_kim/user/migrations/0003_auto_20201209_1221.py
  students/15th/team1/wonhee_kim/user/migrations/0004_auto_20201210_2038.py
  students/15th/team1/wonhee_kim/user/migrations/__init__.py
  students/15th/team1/wonhee_kim/user/models.py
  students/15th/team1/wonhee_kim/user/tests.py
  students/15th/team1/wonhee_kim/user/urls.py
  students/15th/team1/wonhee_kim/user/utils.py
  students/15th/team1/wonhee_kim/user/views/follow_views.py
  students/15th/team1/wonhee_kim/user/views/login_views.py
  students/15th/team1/wonhee_kim/user/views/signup_views.py
  students/15th/team1/wonhee_kim/westargram/settings.py
  students/15th/team1/wonhee_kim/westargram/urls.py
Labels: Status : 리뷰 요청

#161 [15기 김승재] ADD : [MISSION 9] 게시물 및 댓글 수정기능 추가
  students/15th/team4/seungjae_kim/.gitignore
  students/15th/team4/seungjae_kim/manage.py
  students/15th/team4/seungjae_kim/posting/__init__.py
  students/15th/team4/seungjae_kim/posting/admin.py
  students/15th/team4/seungjae_kim/posting/apps.py
  students/15th/team4/seungjae_kim/posting/migrations/0001_initial.py
  students/15th/team4/seungjae_kim/posting/migrations/0002_comments.py
  students/15th/team4/seungjae_kim/posting/migrations/0003_auto_20201209_1827.py
  students/15th/team4/seungjae_kim/posting/migrations/0004_auto_20201211_1310.py
  students/15th/team4/seungjae_kim/posting/migrations/0005_auto_20201211_1622.py
  students/15th/team4/seungjae_kim/posting/migrations/__init__.py
  students/15th/team4/seungjae_kim/posting/models.py
  students/15th/team4/seungjae_kim/posting/tests.py
  students/15th/team4/seungjae_kim/posting/urls.py
  students/15th/team4/seungjae_kim/posting/views.py
  students/15th/team4/seungjae_kim/requirements.txt
  students/15th/team4/seungjae_kim/user/__init__.py
  students/15th/team4/seungjae_kim/user/admin.py
  students/15th/team4/seungjae_kim/user/apps.py
  students/15th/team4/seungjae_kim/user/migrations/0001_initial.py
  students/15th/team4/seungjae_kim/user/migrations/0002_auto_20201209_1107.py
  students/15th/team4/seungjae_kim/user/migrations/0003_users_followers.py
  students/15th/team4/seungjae_kim/user/migrations/0004_auto_20201211_1310.py
  students/15th/team4/seungjae_kim/user/migrations/__init__.py
  students/15th/team4/seungjae_kim/user/models.py
  students/15th/team4/seungjae_kim/user/tests.py
  students/15th/team4/seungjae_kim/user/urls.py
  students/15th/team4/seungjae_kim/user/utils.py
  students/15th/team4/seungjae_kim/user/views.py
  students/15th/team4/seungjae_kim/westagram/__init__.py
  students/15th/team4/seungjae_kim/westagram/asgi.py
  students/15th/team4/seungjae_kim/westagram/settings.py
  students/15th/team4/seungjae_kim/westagram/urls.py
  students/15th/team4/seungjae_kim/westagram/wsgi.py
Labels: Status : 리뷰 요청

#175 [16기 김건희] Mission 1 : Django 초기 세팅
  students/16th/team2/konhee-kim/.gitignore
  students/16th/team2/konhee-kim/manage.py
  students/16th/team2/konhee-kim/requirements.txt
  students/16th/team2/konhee-kim/user/__init__.py
  students/16th/team2/konhee-kim/user/admin.py
  students/16th/team2/konhee-kim/user/apps.py
  students/16th/team2/konhee-kim/user/migrations/__init__.py
  students/16th/team2/konhee-kim/user/models.py
  students/16th/team2/konhee-kim/user/tests.py
  students/16th/team2/konhee-kim/user/views.py
  students/16th/team2/konhee-kim/westagram/__init__.py
  students/16th/team2/konhee-kim/westagram/asgi.py
  students/16th/team2/konhee-kim/westagram/settings.py
  students/16th/team2/konhee-kim/westagram/urls.py
  students/16th/team2/konhee-kim/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항

#172 [16기 최수아] Mission 1 : Django 초기 세팅
  students/16th/team2/suaChoi/.gitignore
  students/16th/team2/suaChoi/manage.py
  students/16th/team2/suaChoi/requirements.txt
  students/16th/team2/suaChoi/user/__init__.py
  students/16th/team2/suaChoi/user/admin.py
  students/16th/team2/suaChoi/user/apps.py
  students/16th/team2/suaChoi/user/migrations/__init__.py
  students/16th/team2/suaChoi/user/models.py
  students/16th/team2/suaChoi/user/tests.py
  students/16th/team2/suaChoi/user/views.py
  students/16th/team2/suaChoi/westagram/__init__.py
  students/16th/team2/suaChoi/westagram/asgi.py
  students/16th/team2/suaChoi/westagram/settings.py
  students/16th/team2/suaChoi/westagram/urls.py
  students/16th/team2/suaChoi/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#174 [16기 조하민] Mission 1 : Django 초기 세팅
  .gitignore
  students/16th/team2/hamin-jo/westagram/manage.py
  students/16th/team2/hamin-jo/westagram/sign/__init__.py
  students/16th/team2/hamin-jo/westagram/sign/admin.py
  students/16th/team2/hamin-jo/westagram/sign/apps.py
  students/16th/team2/hamin-jo/westagram/sign/migrations/__init__.py
  students/16th/team2/hamin-jo/westagram/sign/models.py
  students/16th/team2/hamin-jo/westagram/sign/tests.py
  students/16th/team2/hamin-jo/westagram/sign/urls.py
  students/16th/team2/hamin-jo/westagram/sign/views.py
  students/16th/team2/hamin-jo/westagram/westagram/__init__.py
  students/16th/team2/hamin-jo/westagram/westagram/asgi.py
  students/16th/team2/hamin-jo/westagram/westagram/requirements.txt
  students/16th/team2/hamin-jo/westagram/westagram/settings.py
  students/16th/team2/hamin-jo/westagram/westagram/urls.py
  students/16th/team2/hamin-jo/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#173 [16기 윤정민] Mission 1 : Django 초기 세팅
  students/16th/team2/jmyoon/westagram/.gitignore
  students/16th/team2/jmyoon/westagram/manage.py
  students/16th/team2/jmyoon/westagram/user/__init__.py
  students/16th/team2/jmyoon/westagram/user/admin.py
  students/16th/team2/jmyoon/westagram/user/apps.py
  students/16th/team2/jmyoon/westagram/user/migrations/0001_initial.py
  students/16th/team2/jmyoon/westagram/user/migrations/__init__.py
  students/16th/team2/jmyoon/westagram/user/models.py
  students/16th/team2/jmyoon/westagram/user/tests.py
  students/16th/team2/jmyoon/westagram/user/views.py
  students/16th/team2/jmyoon/westagram/westagram/__init__.py
  students/16th/team2/jmyoon/westagram/westagram/asgi.py
  students/16th/team2/jmyoon/westagram/westagram/settings.py
  students/16th/team2/jmyoon/westagram/westagram/urls.py
  students/16th/team2/jmyoon/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#177 [16기 정지원] Mission 1 : Django 초기 설정
  students/16th/team2/jungjiwon/westagram/.gitignore
  students/16th/team2/jungjiwon/westagram/manage.py
  students/16th/team2/jungjiwon/westagram/requirements.txt
  students/16th/team2/jungjiwon/westagram/user/__init__.py
  students/16th/team2/jungjiwon/westagram/user/admin.py
  students/16th/team2/jungjiwon/westagram/user/apps.py
  students/16th/team2/jungjiwon/westagram/user/migrations/__init__.py
  students/16th/team2/jungjiwon/westagram/user/models.py
  students/16th/team2/jungjiwon/westagram/user/tests.py
  students/16th/team2/jungjiwon/westagram/user/views.py
  students/16th/team2/jungjiwon/westagram/westagram/__init__.py
  students/16th/team2/jungjiwon/westagram/westagram/asgi.py
  students/16th/team2/jungjiwon/westagram/westagram/settings.py
  students/16th/team2/jungjiwon/westagram/westagram/urls.py
  students/16th/team2/jungjiwon/westagram/westagram/views.py
  students/16th/team2/jungjiwon/westagram/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항
