Repository wecode-bootcamp-korea/westagram-backend, pull requests merged in 2020-08, with the labels that each got.

#28 [이태현] Mission 5_피드백 수정
  students/11th/taehyunlee/westagram/Post/__init__.py
  students/11th/taehyunlee/westagram/Post/admin.py
  students/11th/taehyunlee/westagram/Post/apps.py
  students/11th/taehyunlee/westagram/Post/migrations/0001_initial.py
  students/11th/taehyunlee/westagram/Post/migrations/0002_auto_20200803_0146.py
  students/11th/taehyunlee/westagram/Post/migrations/0003_auto_20200803_0436.py
  students/11th/taehyunlee/westagram/Post/migrations/0004_auto_20200803_0452.py
  students/11th/taehyunlee/westagram/Post/migrations/0005_auto_20200803_0738.py
  students/11th/taehyunlee/westagram/Post/migrations/0006_auto_20200803_0812.py
  students/11th/taehyunlee/westagram/Post/migrations/0007_auto_20200803_0814.py
  students/11th/taehyunlee/westagram/Post/migrations/0008_auto_20200803_0821.py
  students/11th/taehyunlee/westagram/Post/migrations/0009_delete_post.py
  students/11th/taehyunlee/westagram/Post/migrations/0010_post.py
  students/11th/taehyunlee/westagram/Post/migrations/0011_comment.py
  students/11th/taehyunlee/westagram/Post/migrations/0012_auto_20200803_1222.py
  students/11th/taehyunlee/westagram/Post/migrations/__init__.py
  students/11th/taehyunlee/westagram/Post/models.py
  students/11th/taehyunlee/westagram/Post/tests.py
  students/11th/taehyunlee/westagram/Post/urls.py
  students/11th/taehyunlee/westagram/Post/views.py
  students/11th/taehyunlee/westagram/User/__init__.py
  students/11th/taehyunlee/westagram/User/admin.py
  students/11th/taehyunlee/westagram/User/apps.py
  students/11th/taehyunlee/westagram/User/migrations/0001_initial.py
  students/11th/taehyunlee/westagram/User/migrations/0002_auto_20200803_0705.py
  students/11th/taehyunlee/westagram/User/migrations/__init__.py
  students/11th/taehyunlee/westagram/User/models.py
  students/11th/taehyunlee/westagram/User/tests.py
  students/11th/taehyunlee/westagram/User/urls.py
  students/11th/taehyunlee/westagram/User/views.py
  students/11th/taehyunlee/westagram/manage.py
  students/11th/taehyunlee/westagram/westagram/__init__.py
  students/11th/taehyunlee/westagram/westagram/asgi.py
  students/11th/taehyunlee/westagram/westagram/settings.py
  students/11th/taehyunlee/westagram/westagram/urls.py
  students/11th/taehyunlee/westagram/westagram/wsgi.py
Labels: Status : 수정 요청, 추가 구현 사항, 필수 구현 사항

#36 [건규] Mission 3 로그인 엔드포인트
  students/11th/kungyulee/.gitignore
  students/11th/kungyulee/accounts/__init__.py
  students/11th/kungyulee/accounts/admin.py
  students/11th/kungyulee/accounts/apps.py
  students/11th/kungyulee/accounts/migrations/0001_initial.py
  students/11th/kungyulee/accounts/migrations/0002_auto_20200803_0927.py
  students/11th/kungyulee/accounts/migrations/0003_user_is_admin.py
  students/11th/kungyulee/accounts/migrations/__init__.py
  students/11th/kungyulee/accounts/models.py
  students/11th/kungyulee/accounts/tests.py
  students/11th/kungyulee/accounts/urls.py
  students/11th/kungyulee/accounts/validators.py
  students/11th/kungyulee/accounts/views.py
  students/11th/kungyulee/manage.py
  students/11th/kungyulee/posts/__init__.py
  students/11th/kungyulee/posts/admin.py
  students/11th/kungyulee/posts/apps.py
  students/11th/kungyulee/posts/decorators.py
  students/11th/kungyulee/posts/migrations/0001_initial.py
  students/11th/kungyulee/posts/migrations/0002_post_date.py
  students/11th/kungyulee/posts/migrations/0003_comment.py
  students/11th/kungyulee/posts/migrations/0004_auto_20200804_0712.py
  students/11th/kungyulee/posts/migrations/__init__.py
  students/11th/kungyulee/posts/models.py
  students/11th/kungyulee/posts/tests.py
  students/11th/kungyulee/posts/urls.py
  students/11th/kungyulee/posts/views.py
  students/11th/kungyulee/westagram/__init__.py
  students/11th/kungyulee/westagram/asgi.py
  students/11th/kungyulee/westagram/settings.py
  students/11th/kungyulee/westagram/urls.py
  students/11th/kungyulee/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#39 [지원] Mission 5 댓글 등록
  students/11th/jiwonko/project/Posting/__init__.py
  students/11th/jiwonko/project/Posting/admin.py
  students/11th/jiwonko/project/Posting/apps.py
  students/11th/jiwonko/project/Posting/migrations/0001_initial.py
  students/11th/jiwonko/project/Posting/migrations/0002_auto_20200805_1110.py
  students/11th/jiwonko/project/Posting/migrations/0003_auto_20200805_1339.py
  students/11th/jiwonko/project/Posting/migrations/0004_post_img_url.py
  students/11th/jiwonko/project/Posting/migrations/0005_comment.py
  students/11th/jiwonko/project/Posting/migrations/0006_auto_20200806_1722.py
  students/11th/jiwonko/project/Posting/migrations/__init__.py
  students/11th/jiwonko/project/Posting/models.py
  students/11th/jiwonko/project/Posting/tests.py
  students/11th/jiwonko/project/Posting/urls.py
  students/11th/jiwonko/project/Posting/views.py
  students/11th/jiwonko/project/User/__init__.py
  students/11th/jiwonko/project/User/admin.py
  students/11th/jiwonko/project/User/apps.py
  students/11th/jiwonko/project/User/migrations/0001_initial.py
  students/11th/jiwonko/project/User/migrations/0002_auto_20200805_1106.py
  students/11th/jiwonko/project/User/migrations/0003_auto_20200812_1307.py
  students/11th/jiwonko/project/User/migrations/__init__.py
  students/11th/jiwonko/project/User/models.py
  students/11th/jiwonko/project/User/tests.py
  students/11th/jiwonko/project/User/urls.py
  students/11th/jiwonko/project/User/utils.py
  students/11th/jiwonko/project/User/validators.py
  students/11th/jiwonko/project/User/views.py
  students/11th/jiwonko/project/manage.py
  students/11th/jiwonko/project/project/__init__.py
  students/11th/jiwonko/project/project/asgi.py
  students/11th/jiwonko/project/project/settings.py
  students/11th/jiwonko/project/project/urls.py
  students/11th/jiwonko/project/project/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#42 [왕민욱] Mission 5 게시물에 댓글 등록
  students/minwook/westagram_back/Posting/__init__.py
  students/minwook/westagram_back/Posting/admin.py
  students/minwook/westagram_back/Posting/apps.py
  students/minwook/westagram_back/Posting/migrations/0001_initial.py
  students/minwook/westagram_back/Posting/migrations/__init__.py
  students/minwook/westagram_back/Posting/models.py
  students/minwook/westagram_back/Posting/tests.py
  students/minwook/westagram_back/Posting/urls.py
  students/minwook/westagram_back/Posting/views.py
  students/minwook/westagram_back/User/__init__.py
  students/minwook/westagram_back/User/admin.py
  students/minwook/westagram_back/User/apps.py
  students/minwook/westagram_back/User/migrations/0001_initial.py
  students/minwook/westagram_back/User/migrations/__init__.py
  students/minwook/westagram_back/User/models.py
  students/minwook/westagram_back/User/tests.py
  students/minwook/westagram_back/User/urls.py
  students/minwook/westagram_back/User/views.py
  students/minwook/westagram_back/manage.py
  students/minwook/westagram_back/westagram_back/__init__.py
  students/minwook/westagram_back/westagram_back/asgi.py
  students/minwook/westagram_back/westagram_back/settings.py
  students/minwook/westagram_back/westagram_back/urls.py
  students/minwook/westagram_back/westagram_back/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#29 [김태수] Mission7 Commit
  .gitignore
  students/11th/taesukim/project/Posting/__init__.py
  students/11th/taesukim/project/Posting/admin.py
  students/11th/taesukim/project/Posting/apps.py
  students/11th/taesukim/project/Posting/migrations/0001_initial.py
  students/11th/taesukim/project/Posting/migrations/0002_auto_20200804_1852.py
  students/11th/taesukim/project/Posting/migrations/0003_auto_20200813_2004.py
  students/11th/taesukim/project/Posting/migrations/__init__.py
  students/11th/taesukim/project/Posting/models.py
  students/11th/taesukim/project/Posting/tests.py
  students/11th/taesukim/project/Posting/urls.py
  students/11th/taesukim/project/Posting/views.py
  students/11th/taesukim/project/User/__init__.py
  students/11th/taesukim/project/User/admin.py
  students/11th/taesukim/project/User/apps.py
  students/11th/taesukim/project/User/helper.py
  students/11th/taesukim/project/User/migrations/0001_initial.py
  students/11th/taesukim/project/User/migrations/0002_auto_20200804_0204.py
  students/11th/taesukim/project/User/migrations/0003_follow.py
  students/11th/taesukim/project/User/migrations/__init__.py
  students/11th/taesukim/project/User/models.py
  students/11th/taesukim/project/User/tests.py
  students/11th/taesukim/project/User/urls.py
  students/11th/taesukim/project/User/utils.py
  students/11th/taesukim/project/User/views.py
  students/11th/taesukim/project/manage.py
  students/11th/taesukim/project/project/__init__.py
  students/11th/taesukim/project/project/asgi.py
  students/11th/taesukim/project/project/settings.py
  students/11th/taesukim/project/project/urls.py
  students/11th/taesukim/project/project/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#40 [창식] mission5 댓글 수정완료
  students/10th/leemun0/mysite1/.DS_Store
  students/11th/changsik/westagram/.vscode/settings.json
  students/11th/changsik/westagram/manage.py
  students/11th/changsik/westagram/post/__init__.py
  students/11th/changsik/westagram/post/admin.py
  students/11th/changsik/westagram/post/apps.py
  students/11th/changsik/westagram/post/migrations/0001_initial.py
  students/11th/changsik/westagram/post/migrations/0002_post_img_url.py
  students/11th/changsik/westagram/post/migrations/0003_auto_20200805_1706.py
  students/11th/changsik/westagram/post/migrations/0004_auto_20200806_1442.py
  students/11th/changsik/westagram/post/migrations/__init__.py
  students/11th/changsik/westagram/post/models.py
  students/11th/changsik/westagram/post/tests.py
  students/11th/changsik/westagram/post/urls.py
  students/11th/changsik/westagram/post/views.py
  students/11th/changsik/westagram/user/__init__.py
  students/11th/changsik/westagram/user/admin.py
  students/11th/changsik/westagram/user/apps.py
  students/11th/changsik/westagram/user/migrations/0001_initial.py
  students/11th/changsik/westagram/user/migrations/0002_auto_20200803_2006.py
  students/11th/changsik/westagram/user/migrations/0003_auto_20200804_1600.py
  students/11th/changsik/westagram/user/migrations/0004_auto_20200805_1908.py
  students/11th/changsik/westagram/user/migrations/__init__.py
  students/11th/changsik/westagram/user/models.py
  students/11th/changsik/westagram/user/tests.py
  students/11th/changsik/westagram/user/urls.py
  students/11th/changsik/westagram/user/views.py
  students/11th/changsik/westagram/westagram/__init__.py
  students/11th/changsik/westagram/westagram/asgi.py
  students/11th/changsik/westagram/westagram/settings.py
  students/11th/changsik/westagram/westagram/urls.py
  students/11th/changsik/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#41 [이충희] 미션5 - 게시물에 댓글 등록
  students/11th/choonghee-lee/.gitignore
  students/11th/choonghee-lee/account/__init__.py
  students/11th/choonghee-lee/account/admin.py
  students/11th/choonghee-lee/account/apps.py
  students/11th/choonghee-lee/account/migrations/0001_initial.py
  students/11th/choonghee-lee/account/migrations/__init__.py
  students/11th/choonghee-lee/account/models.py
  students/11th/choonghee-lee/account/tests.py
  students/11th/choonghee-lee/account/urls.py
  students/11th/choonghee-lee/account/views.py
  students/11th/choonghee-lee/config/__init__.py
  students/11th/choonghee-lee/config/asgi.py
  students/11th/choonghee-lee/config/settings.py
  students/11th/choonghee-lee/config/urls.py
  students/11th/choonghee-lee/config/wsgi.py
  students/11th/choonghee-lee/manage.py
  students/11th/choonghee-lee/posting/__init__.py
  students/11th/choonghee-lee/posting/admin.py
  students/11th/choonghee-lee/posting/apps.py
  students/11th/choonghee-lee/posting/migrations/0001_initial.py
  students/11th/choonghee-lee/posting/migrations/__init__.py
  students/11th/choonghee-lee/posting/models.py
  students/11th/choonghee-lee/posting/tests.py
  students/11th/choonghee-lee/posting/urls.py
  students/11th/choonghee-lee/posting/views.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#43 [해준] Mission.5 게시물에 댓글 등록 구현 및 피드백 수정
  students/11th/haejunkim/westagram/.gitignore
  students/11th/haejunkim/westagram/Post/__init__.py
  students/11th/haejunkim/westagram/Post/admin.py
  students/11th/haejunkim/westagram/Post/apps.py
  students/11th/haejunkim/westagram/Post/migrations/0001_initial.py
  students/11th/haejunkim/westagram/Post/migrations/0002_auto_20200805_1929.py
  students/11th/haejunkim/westagram/Post/migrations/0003_auto_20200806_1236.py
  students/11th/haejunkim/westagram/Post/migrations/0004_comment.py
  students/11th/haejunkim/westagram/Post/migrations/__init__.py
  students/11th/haejunkim/westagram/Post/models.py
  students/11th/haejunkim/westagram/Post/tests.py
  students/11th/haejunkim/westagram/Post/urls.py
  students/11th/haejunkim/westagram/Post/views.py
  students/11th/haejunkim/westagram/User/__init__.py
  students/11th/haejunkim/westagram/User/admin.py
  students/11th/haejunkim/westagram/User/apps.py
  students/11th/haejunkim/westagram/User/migrations/0001_initial.py
  students/11th/haejunkim/westagram/User/migrations/0002_auto_20200803_2127.py
  students/11th/haejunkim/westagram/User/migrations/0003_auto_20200805_1833.py
  students/11th/haejunkim/westagram/User/migrations/__init__.py
  students/11th/haejunkim/westagram/User/models.py
  students/11th/haejunkim/westagram/User/tests.py
  students/11th/haejunkim/westagram/User/urls.py
  students/11th/haejunkim/westagram/User/utils.py
  students/11th/haejunkim/westagram/User/validation.py
  students/11th/haejunkim/westagram/User/views.py
  students/11th/haejunkim/westagram/manage.py
  students/11th/haejunkim/westagram/settings.json
  students/11th/haejunkim/westagram/westagram/__init__.py
  students/11th/haejunkim/westagram/westagram/asgi.py
  students/11th/haejunkim/westagram/westagram/settings.py
  students/11th/haejunkim/westagram/westagram/urls.py
  students/11th/haejunkim/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#44 [김기욱] Mission4,5 : 포스트, 댓글 기능 구현완료
  students/11th/Keywookkim/westagram/.vscode/settings.json
  students/11th/Keywookkim/westagram/Post/__init__.py
  students/11th/Keywookkim/westagram/Post/admin.py
  students/11th/Keywookkim/westagram/Post/apps.py
  students/11th/Keywookkim/westagram/Post/models.py
  students/11th/Keywookkim/westagram/Post/tests.py
  students/11th/Keywookkim/westagram/Post/urls.py
  students/11th/Keywookkim/westagram/Post/views.py
  students/11th/Keywookkim/westagram/User/__init__.py
  students/11th/Keywookkim/westagram/User/admin.py
  students/11th/Keywookkim/westagram/User/apps.py
  students/11th/Keywookkim/westagram/User/migrations/0001_initial.py
  students/11th/Keywookkim/westagram/User/migrations/__init__.py
  students/11th/Keywookkim/westagram/User/models.py
  students/11th/Keywookkim/westagram/User/my_settings.py
  students/11th/Keywookkim/westagram/User/tests.py
  students/11th/Keywookkim/westagram/User/urls.py
  students/11th/Keywookkim/westagram/User/validators.py
  students/11th/Keywookkim/westagram/User/views.py
  students/11th/Keywookkim/westagram/manage.py
  students/11th/Keywookkim/westagram/requirements.txt
  students/11th/Keywookkim/westagram/westagram/__init__.py
  students/11th/Keywookkim/westagram/westagram/asgi.py
  students/11th/Keywookkim/westagram/westagram/settings.py
  students/11th/Keywookkim/westagram/westagram/urls.py
  students/11th/Keywookkim/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#46 [문태기] Mission 2, 3, 4, 5(회원가입, 로그인, 게시물, 게시물댓글) 기능 구현완료
  students/11th/moontaegi/.vscode/settings.json
  students/11th/moontaegi/manage.py
  students/11th/moontaegi/posting/__init__.py
  students/11th/moontaegi/posting/admin.py
  students/11th/moontaegi/posting/apps.py
  students/11th/moontaegi/posting/migrations/0001_initial.py
  students/11th/moontaegi/posting/migrations/0002_auto_20200810_0802.py
  students/11th/moontaegi/posting/migrations/0003_comment.py
  students/11th/moontaegi/posting/migrations/0004_auto_20200810_2309.py
  students/11th/moontaegi/posting/migrations/0005_auto_20200812_1303.py
  students/11th/moontaegi/posting/migrations/__init__.py
  students/11th/moontaegi/posting/models.py
  students/11th/moontaegi/posting/tests.py
  students/11th/moontaegi/posting/urls.py
  students/11th/moontaegi/posting/views.py
  students/11th/moontaegi/user/__init__.py
  students/11th/moontaegi/user/admin.py
  students/11th/moontaegi/user/apps.py
  students/11th/moontaegi/user/migrations/0001_initial.py
  students/11th/moontaegi/user/migrations/0002_auto_20200807_1404.py
  students/11th/moontaegi/user/migrations/0003_auto_20200811_1952.py
  students/11th/moontaegi/user/migrations/0004_auto_20200812_1536.py
  students/11th/moontaegi/user/migrations/__init__.py
  students/11th/moontaegi/user/models.py
  students/11th/moontaegi/user/tests.py
  students/11th/moontaegi/user/urls.py
  students/11th/moontaegi/user/validator.py
  students/11th/moontaegi/user/views.py
  students/11th/moontaegi/westagram/__init__.py
  students/11th/moontaegi/westagram/asgi.py
  students/11th/moontaegi/westagram/settings.py
  students/11th/moontaegi/westagram/urls.py
  students/11th/moontaegi/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#47 [태하] 미션 5 완료
  students/11th/taehakim/westa/.vscode/settings.json
  students/11th/taehakim/westa/Account/__init__.py
  students/11th/taehakim/westa/Account/admin.py
  students/11th/taehakim/westa/Account/apps.py
  students/11th/taehakim/westa/Account/migrations/0001_initial.py
  students/11th/taehakim/westa/Account/migrations/0002_auto_20200807_0958.py
  students/11th/taehakim/westa/Account/migrations/0003_auto_20200807_1142.py
  students/11th/taehakim/westa/Account/migrations/0004_auto_20200807_1247.py
  students/11th/taehakim/westa/Account/migrations/0005_auto_20200807_1250.py
  students/11th/taehakim/westa/Account/migrations/__init__.py
  students/11th/taehakim/westa/Account/models.py
  students/11th/taehakim/westa/Account/tests.py
  students/11th/taehakim/westa/Account/urls.py
  students/11th/taehakim/westa/Account/views.py
  students/11th/taehakim/westa/Posting/__init__.py
  students/11th/taehakim/westa/Posting/admin.py
  students/11th/taehakim/westa/Posting/apps.py
  students/11th/taehakim/westa/Posting/migrations/0001_initial.py
  students/11th/taehakim/westa/Posting/migrations/0002_comment.py
  students/11th/taehakim/westa/Posting/migrations/__init__.py
  students/11th/taehakim/westa/Posting/models.py
  students/11th/taehakim/westa/Posting/tests.py
  students/11th/taehakim/westa/Posting/urls.py
  students/11th/taehakim/westa/Posting/views.py
  students/11th/taehakim/westa/manage.py
  students/11th/taehakim/westa/westa/__init__.py
  students/11th/taehakim/westa/westa/asgi.py
  students/11th/taehakim/westa/westa/settings.py
  students/11th/taehakim/westa/westa/urls.py
  students/11th/taehakim/westa/westa/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#48 [김현우] Mission 5 수정완료
  students/11th/kimhyunwoo/westagram/account/__init__.py
  students/11th/kimhyunwoo/westagram/account/admin.py
  students/11th/kimhyunwoo/westagram/account/apps.py
  students/11th/kimhyunwoo/westagram/account/migrations/0001_initial.py
  students/11th/kimhyunwoo/westagram/account/migrations/0002_auto_20200810_0815.py
  students/11th/kimhyunwoo/westagram/account/migrations/__init__.py
  students/11th/kimhyunwoo/westagram/account/models.py
  students/11th/kimhyunwoo/westagram/account/tests.py
  students/11th/kimhyunwoo/westagram/account/urls.py
  students/11th/kimhyunwoo/westagram/account/views.py
  students/11th/kimhyunwoo/westagram/manage.py
  students/11th/kimhyunwoo/westagram/posting/__init__.py
  students/11th/kimhyunwoo/westagram/posting/admin.py
  students/11th/kimhyunwoo/westagram/posting/apps.py
  students/11th/kimhyunwoo/westagram/posting/migrations/0001_initial.py
  students/11th/kimhyunwoo/westagram/posting/migrations/0002_auto_20200810_0928.py
  students/11th/kimhyunwoo/westagram/posting/migrations/0003_comment.py
  students/11th/kimhyunwoo/westagram/posting/migrations/__init__.py
  students/11th/kimhyunwoo/westagram/posting/models.py
  students/11th/kimhyunwoo/westagram/posting/tests.py
  students/11th/kimhyunwoo/westagram/posting/urls.py
  students/11th/kimhyunwoo/westagram/posting/views.py
  students/11th/kimhyunwoo/westagram/westagram/__init__.py
  students/11th/kimhyunwoo/westagram/westagram/asgi.py
  students/11th/kimhyunwoo/westagram/westagram/settings.py
  students/11th/kimhyunwoo/westagram/westagram/urls.py
  students/11th/kimhyunwoo/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항
