Repository wecode-bootcamp-korea/westagram-backend, pull requests merged in 2021-01, with the labels that each got.

#184 [16기 이동규] Mission 1 : Django 초기 설정
  students/16th/team2/donq-lee/westagram/.gitignore
  students/16th/team2/donq-lee/westagram/manage.py
  students/16th/team2/donq-lee/westagram/westagram/__init__.py
  students/16th/team2/donq-lee/westagram/westagram/asgi.py
  students/16th/team2/donq-lee/westagram/westagram/settings.py
  students/16th/team2/donq-lee/westagram/westagram/urls.py
  students/16th/team2/donq-lee/westagram/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#189 [이동규] Mission 3: 로그인 엔드포인트_암호,토큰 추가
  students/16th/team2/donq-lee/westagram/.gitignore
  students/16th/team2/donq-lee/westagram/posting/__init__.py
  students/16th/team2/donq-lee/westagram/posting/admin.py
  students/16th/team2/donq-lee/westagram/posting/apps.py
  students/16th/team2/donq-lee/westagram/posting/migrations/__init__.py
  students/16th/team2/donq-lee/westagram/posting/models.py
  students/16th/team2/donq-lee/westagram/posting/tests.py
  students/16th/team2/donq-lee/westagram/posting/urls.py
  students/16th/team2/donq-lee/westagram/posting/views.py
  students/16th/team2/donq-lee/westagram/user/__init__.py
  students/16th/team2/donq-lee/westagram/user/admin.py
  students/16th/team2/donq-lee/westagram/user/apps.py
  students/16th/team2/donq-lee/westagram/user/migrations/0001_initial.py
  students/16th/team2/donq-lee/westagram/user/migrations/0002_auto_20210104_2233.py
  students/16th/team2/donq-lee/westagram/user/migrations/0003_auto_20210105_1618.py
  students/16th/team2/donq-lee/westagram/user/migrations/0004_auto_20210105_1635.py
  students/16th/team2/donq-lee/westagram/user/migrations/0005_auto_20210105_1636.py
  students/16th/team2/donq-lee/westagram/user/migrations/0006_auto_20210105_1636.py
  students/16th/team2/donq-lee/westagram/user/migrations/0007_auto_20210105_1659.py
  students/16th/team2/donq-lee/westagram/user/migrations/0008_auto_20210106_1522.py
  students/16th/team2/donq-lee/westagram/user/migrations/__init__.py
  students/16th/team2/donq-lee/westagram/user/models.py
  students/16th/team2/donq-lee/westagram/user/tests.py
  students/16th/team2/donq-lee/westagram/user/urls.py
  students/16th/team2/donq-lee/westagram/user/views.py
  students/16th/team2/donq-lee/westagram/westagram/settings.py
  students/16th/team2/donq-lee/westagram/westagram/urls.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#183 [윤정민] Mission 4: 게시물등록
  students/16th/team2/jmyoon/westagram/post/__init__.py
  students/16th/team2/jmyoon/westagram/post/admin.py
  students/16th/team2/jmyoon/westagram/post/apps.py
  students/16th/team2/jmyoon/westagram/post/migrations/0001_initial.py
  students/16th/team2/jmyoon/westagram/post/migrations/0002_auto_20210106_0001.py
  students/16th/team2/jmyoon/westagram/post/migrations/__init__.py
  students/16th/team2/jmyoon/westagram/post/models.py
  students/16th/team2/jmyoon/westagram/post/tests.py
  students/16th/team2/jmyoon/westagram/post/urls.py
  students/16th/team2/jmyoon/westagram/post/views.py
  students/16th/team2/jmyoon/westagram/user/migrations/0002_auto_20201231_1140.py
  students/16th/team2/jmyoon/westagram/user/migrations/0003_auto_20210105_1552.py
  students/16th/team2/jmyoon/westagram/user/migrations/0004_auto_20210105_1601.py
  students/16th/team2/jmyoon/westagram/user/migrations/0005_auto_20210105_1621.py
  students/16th/team2/jmyoon/westagram/user/migrations/0006_auto_20210107_0417.py
  students/16th/team2/jmyoon/westagram/user/models.py
  students/16th/team2/jmyoon/westagram/user/urls.py
  students/16th/team2/jmyoon/westagram/user/views.py
  students/16th/team2/jmyoon/westagram/westagram/settings.py
  students/16th/team2/jmyoon/westagram/westagram/urls.py
Labels: Status : 수정 요청, 필수 구현 사항

#181 [최수아] Mission 6 : 게시물 '좋아요' 기능 구현
  students/16th/team2/suaChoi/posting/__init__.py
  students/16th/team2/suaChoi/posting/admin.py
  students/16th/team2/suaChoi/posting/apps.py
  students/16th/team2/suaChoi/posting/migrations/0001_initial.py
  students/16th/team2/suaChoi/posting/migrations/0002_auto_20210105_1458.py
  students/16th/team2/suaChoi/posting/migrations/0003_post_content.py
  students/16th/team2/suaChoi/posting/migrations/0004_auto_20210106_1301.py
  students/16th/team2/suaChoi/posting/migrations/0005_comment.py
  students/16th/team2/suaChoi/posting/migrations/0006_like.py
  students/16th/team2/suaChoi/posting/migrations/0007_comment_post.py
  students/16th/team2/suaChoi/posting/migrations/0008_auto_20210109_1818.py
  students/16th/team2/suaChoi/posting/migrations/0009_auto_20210109_1911.py
  students/16th/team2/suaChoi/posting/migrations/0010_auto_20210109_1921.py
  students/16th/team2/suaChoi/posting/migrations/__init__.py
  students/16th/team2/suaChoi/posting/models.py
  students/16th/team2/suaChoi/posting/tests.py
  students/16th/team2/suaChoi/posting/urls.py
  students/16th/team2/suaChoi/posting/views.py
  students/16th/team2/suaChoi/user/migrations/0001_initial.py
  students/16th/team2/suaChoi/user/migrations/0002_auto_20210104_0944.py
  students/16th/team2/suaChoi/user/migrations/0003_user_user_id.py
  students/16th/team2/suaChoi/user/migrations/0004_auto_20210104_1010.py
  students/16th/team2/suaChoi/user/migrations/0005_auto_20210104_1123.py
  students/16th/team2/suaChoi/user/models.py
  students/16th/team2/suaChoi/user/urls.py
  students/16th/team2/suaChoi/user/utils.py
  students/16th/team2/suaChoi/user/views.py
  students/16th/team2/suaChoi/westagram/settings.py
  students/16th/team2/suaChoi/westagram/urls.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#179 [김건희] Mission 6: 좋아요 기능
  students/16th/team2/konhee-kim/posting/__init__.py
  students/16th/team2/konhee-kim/posting/admin.py
  students/16th/team2/konhee-kim/posting/apps.py
  students/16th/team2/konhee-kim/posting/migrations/0001_initial.py
  students/16th/team2/konhee-kim/posting/migrations/0002_auto_20210107_1651.py
  students/16th/team2/konhee-kim/posting/migrations/0003_comment.py
  students/16th/team2/konhee-kim/posting/migrations/0004_like.py
  students/16th/team2/konhee-kim/posting/migrations/__init__.py
  students/16th/team2/konhee-kim/posting/models.py
  students/16th/team2/konhee-kim/posting/tests.py
  students/16th/team2/konhee-kim/posting/urls.py
  students/16th/team2/konhee-kim/posting/views.py
  students/16th/team2/konhee-kim/requirements.txt
  students/16th/team2/konhee-kim/user/migrations/0001_initial.py
  students/16th/team2/konhee-kim/user/migrations/0002_auto_20201231_1202.py
  students/16th/team2/konhee-kim/user/migrations/0003_auto_20210107_0702.py
  students/16th/team2/konhee-kim/user/models.py
  students/16th/team2/konhee-kim/user/my_middleware.py
  students/16th/team2/konhee-kim/user/urls.py
  students/16th/team2/konhee-kim/user/utils.py
  students/16th/team2/konhee-kim/user/views.py
  students/16th/team2/konhee-kim/westagram/settings.py
  students/16th/team2/konhee-kim/westagram/urls.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#170 [이혜성]Mission: 9 게시물&댓글 수정 기능
  students/16th/team1/hyeseonglee/.gitignore
  students/16th/team1/hyeseonglee/decorator/utils.py
  students/16th/team1/hyeseonglee/hyeseonglee.zip
  students/16th/team1/hyeseonglee/manage.py
  students/16th/team1/hyeseonglee/posting/__init__.py
  students/16th/team1/hyeseonglee/posting/admin.py
  students/16th/team1/hyeseonglee/posting/apps.py
  students/16th/team1/hyeseonglee/posting/migrations/0001_initial.py
  students/16th/team1/hyeseonglee/posting/migrations/0002_auto_20210109_1149.py
  students/16th/team1/hyeseonglee/posting/migrations/__init__.py
  students/16th/team1/hyeseonglee/posting/models.py
  students/16th/team1/hyeseonglee/posting/tests.py
  students/16th/team1/hyeseonglee/posting/urls.py
  students/16th/team1/hyeseonglee/posting/views.py
  students/16th/team1/hyeseonglee/requirements.txt
  students/16th/team1/hyeseonglee/user/__init__.py
  students/16th/team1/hyeseonglee/user/admin.py
  students/16th/team1/hyeseonglee/user/apps.py
  students/16th/team1/hyeseonglee/user/migrations/0001_initial.py
  students/16th/team1/hyeseonglee/user/migrations/0002_auto_20210106_0513.py
  students/16th/team1/hyeseonglee/user/migrations/0003_auto_20210108_1615.py
  students/16th/team1/hyeseonglee/user/migrations/0004_auto_20210108_1616.py
  students/16th/team1/hyeseonglee/user/migrations/0005_auto_20210108_1619.py
  students/16th/team1/hyeseonglee/user/migrations/__init__.py
  students/16th/team1/hyeseonglee/user/models.py
  students/16th/team1/hyeseonglee/user/tests.py
  students/16th/team1/hyeseonglee/user/urls.py
  students/16th/team1/hyeseonglee/user/views.py
  students/16th/team1/hyeseonglee/westagram/__init__.py
  students/16th/team1/hyeseonglee/westagram/asgi.py
  students/16th/team1/hyeseonglee/westagram/settings.py
  students/16th/team1/hyeseonglee/westagram/urls.py
  students/16th/team1/hyeseonglee/westagram/wsgi.py
  students/16th/team1/seunghyunson/seunghyunson.md
Labels: Status : 수정 요청, 추가 구현 사항

#169 [홍연우] Mission 10: 특정 댓글에 대답하는 '대댓글' 달기
  students/16th/team1/yeonu_hong/.gitignore
  students/16th/team1/yeonu_hong/decorator.py
  students/16th/team1/yeonu_hong/manage.py
  students/16th/team1/yeonu_hong/post/__init__.py
  students/16th/team1/yeonu_hong/post/admin.py
  students/16th/team1/yeonu_hong/post/apps.py
  students/16th/team1/yeonu_hong/post/migrations/0001_initial.py
  students/16th/team1/yeonu_hong/post/migrations/0002_auto_20201230_1121.py
  students/16th/team1/yeonu_hong/post/migrations/0003_comment.py
  students/16th/team1/yeonu_hong/post/migrations/0004_auto_20210103_1244.py
  students/16th/team1/yeonu_hong/post/migrations/0005_auto_20210104_0924.py
  students/16th/team1/yeonu_hong/post/migrations/0006_recomment.py
  students/16th/team1/yeonu_hong/post/migrations/0007_auto_20210106_1137.py
  students/16th/team1/yeonu_hong/post/migrations/__init__.py
  students/16th/team1/yeonu_hong/post/models.py
  students/16th/team1/yeonu_hong/post/tests.py
  students/16th/team1/yeonu_hong/post/urls.py
  students/16th/team1/yeonu_hong/post/views.py
  students/16th/team1/yeonu_hong/requirements.txt
  students/16th/team1/yeonu_hong/user/__init__.py
  students/16th/team1/yeonu_hong/user/admin.py
  students/16th/team1/yeonu_hong/user/apps.py
  students/16th/team1/yeonu_hong/user/migrations/0001_initial.py
  students/16th/team1/yeonu_hong/user/migrations/0002_auto_20201231_0558.py
  students/16th/team1/yeonu_hong/user/migrations/0003_auto_20210104_1109.py
  students/16th/team1/yeonu_hong/user/migrations/0004_auto_20210105_0624.py
  students/16th/team1/yeonu_hong/user/migrations/0005_auto_20210105_0625.py
  students/16th/team1/yeonu_hong/user/migrations/0006_auto_20210105_1132.py
  students/16th/team1/yeonu_hong/user/migrations/0007_auto_20210106_0514.py
  students/16th/team1/yeonu_hong/user/migrations/0008_auto_20210107_1444.py
  students/16th/team1/yeonu_hong/user/migrations/__init__.py
  students/16th/team1/yeonu_hong/user/models.py
  students/16th/team1/yeonu_hong/user/tests.py
  students/16th/team1/yeonu_hong/user/urls.py
  students/16th/team1/yeonu_hong/user/views.py
  students/16th/team1/yeonu_hong/westagram/__init__.py
  students/16th/team1/yeonu_hong/westagram/asgi.py
  students/16th/team1/yeonu_hong/westagram/settings.py
  students/16th/team1/yeonu_hong/westagram/urls.py
  students/16th/team1/yeonu_hong/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#167 [김준형] Mission 10: 대댓글 달기
  students/16th/team1/kimjunhyung/.gitignore
  students/16th/team1/kimjunhyung/decorators/utils.py
  students/16th/team1/kimjunhyung/manage.py
  students/16th/team1/kimjunhyung/posts/__init__.py
  students/16th/team1/kimjunhyung/posts/admin.py
  students/16th/team1/kimjunhyung/posts/apps.py
  students/16th/team1/kimjunhyung/posts/migrations/0001_initial.py
  students/16th/team1/kimjunhyung/posts/migrations/0002_commentbycomment.py
  students/16th/team1/kimjunhyung/posts/migrations/0003_commentbycomment_content.py
  students/16th/team1/kimjunhyung/posts/migrations/0004_auto_20210104_0142.py
  students/16th/team1/kimjunhyung/posts/migrations/0005_auto_20210104_0144.py
  students/16th/team1/kimjunhyung/posts/migrations/__init__.py
  students/16th/team1/kimjunhyung/posts/models.py
  students/16th/team1/kimjunhyung/posts/tests.py
  students/16th/team1/kimjunhyung/posts/urls.py
  students/16th/team1/kimjunhyung/posts/views.py
  students/16th/team1/kimjunhyung/requirements.txt
  students/16th/team1/kimjunhyung/users/__init__.py
  students/16th/team1/kimjunhyung/users/admin.py
  students/16th/team1/kimjunhyung/users/apps.py
  students/16th/team1/kimjunhyung/users/migrations/0001_initial.py
  students/16th/team1/kimjunhyung/users/migrations/0002_auto_20201229_0929.py
  students/16th/team1/kimjunhyung/users/migrations/0003_auto_20201229_1346.py
  students/16th/team1/kimjunhyung/users/migrations/0004_auto_20210104_1732.py
  students/16th/team1/kimjunhyung/users/migrations/0005_auto_20210105_2150.py
  students/16th/team1/kimjunhyung/users/migrations/0006_auto_20210105_2211.py
  students/16th/team1/kimjunhyung/users/migrations/0007_auto_20210105_2213.py
  students/16th/team1/kimjunhyung/users/migrations/__init__.py
  students/16th/team1/kimjunhyung/users/models.py
  students/16th/team1/kimjunhyung/users/tests.py
  students/16th/team1/kimjunhyung/users/urls.py
  students/16th/team1/kimjunhyung/users/views.py
  students/16th/team1/kimjunhyung/westagram/__init__.py
  students/16th/team1/kimjunhyung/westagram/asgi.py
  students/16th/team1/kimjunhyung/westagram/settings.py
  students/16th/team1/kimjunhyung/westagram/settings_test.py
  students/16th/team1/kimjunhyung/westagram/test_runner.py
  students/16th/team1/kimjunhyung/westagram/urls.py
  students/16th/team1/kimjunhyung/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#166 [장준영] Mission 10: 특정 댓글에 대답하는 '대댓글' 달기
  students/16th/team1/junyoungjang/.gitignore
  students/16th/team1/junyoungjang/manage.py
  students/16th/team1/junyoungjang/post/__init__.py
  students/16th/team1/junyoungjang/post/admin.py
  students/16th/team1/junyoungjang/post/apps.py
  students/16th/team1/junyoungjang/post/exception_check.py
  students/16th/team1/junyoungjang/post/migrations/0001_initial.py
  students/16th/team1/junyoungjang/post/migrations/0002_auto_20201230_0654.py
  students/16th/team1/junyoungjang/post/migrations/0003_comment.py
  students/16th/team1/junyoungjang/post/migrations/0004_comment_updated_at.py
  students/16th/team1/junyoungjang/post/migrations/0005_postlike.py
  students/16th/team1/junyoungjang/post/migrations/0006_comment_recomment.py
  students/16th/team1/junyoungjang/post/migrations/__init__.py
  students/16th/team1/junyoungjang/post/models.py
  students/16th/team1/junyoungjang/post/tests.py
  students/16th/team1/junyoungjang/post/urls.py
  students/16th/team1/junyoungjang/post/views.py
  students/16th/team1/junyoungjang/requirements.txt
  students/16th/team1/junyoungjang/user/__init__.py
  students/16th/team1/junyoungjang/user/admin.py
  students/16th/team1/junyoungjang/user/apps.py
  students/16th/team1/junyoungjang/user/exception_check.py
  students/16th/team1/junyoungjang/user/migrations/0001_initial.py
  students/16th/team1/junyoungjang/user/migrations/0002_user_phonenumber.py
  students/16th/team1/junyoungjang/user/migrations/0003_follow.py
  students/16th/team1/junyoungjang/user/migrations/0004_auto_20210105_0723.py
  students/16th/team1/junyoungjang/user/migrations/__init__.py
  students/16th/team1/junyoungjang/user/models.py
  students/16th/team1/junyoungjang/user/tests.py
  students/16th/team1/junyoungjang/user/urls.py
  students/16th/team1/junyoungjang/user/views.py
  students/16th/team1/junyoungjang/westagram/__init__.py
  students/16th/team1/junyoungjang/westagram/asgi.py
  students/16th/team1/junyoungjang/westagram/settings.py
  students/16th/team1/junyoungjang/westagram/urls.py
  students/16th/team1/junyoungjang/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#165 [이성용] Mission 4 진행 중
  students/16th/team1/sungyong_Lee/.gitignore
  students/16th/team1/sungyong_Lee/account/__init__.py
  students/16th/team1/sungyong_Lee/account/admin.py
  students/16th/team1/sungyong_Lee/account/apps.py
  students/16th/team1/sungyong_Lee/account/migrations/0001_initial.py
  students/16th/team1/sungyong_Lee/account/migrations/0002_auto_20201229_1610.py
  students/16th/team1/sungyong_Lee/account/migrations/0003_auto_20201229_1612.py
  students/16th/team1/sungyong_Lee/account/migrations/0004_auto_20210105_0740.py
  students/16th/team1/sungyong_Lee/account/migrations/__init__.py
  students/16th/team1/sungyong_Lee/account/models.py
  students/16th/team1/sungyong_Lee/account/tests.py
  students/16th/team1/sungyong_Lee/account/urls.py
  students/16th/team1/sungyong_Lee/account/views.py
  students/16th/team1/sungyong_Lee/manage.py
  students/16th/team1/sungyong_Lee/post/__init__.py
  students/16th/team1/sungyong_Lee/post/admin.py
  students/16th/team1/sungyong_Lee/post/apps.py
  students/16th/team1/sungyong_Lee/post/migrations/0001_initial.py
  students/16th/team1/sungyong_Lee/post/migrations/__init__.py
  students/16th/team1/sungyong_Lee/post/models.py
  students/16th/team1/sungyong_Lee/post/tests.py
  students/16th/team1/sungyong_Lee/post/urls.py
  students/16th/team1/sungyong_Lee/post/views.py
  students/16th/team1/sungyong_Lee/requirements.txt
  students/16th/team1/sungyong_Lee/utils/__init__.py
  students/16th/team1/sungyong_Lee/utils/decorators.py
  students/16th/team1/sungyong_Lee/utils/descriptors.py
  students/16th/team1/sungyong_Lee/westagram/__init__.py
  students/16th/team1/sungyong_Lee/westagram/asgi.py
  students/16th/team1/sungyong_Lee/westagram/settings.py
  students/16th/team1/sungyong_Lee/westagram/urls.py
  students/16th/team1/sungyong_Lee/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항
