Repository wecode-bootcamp-korea/westagram-backend, pull requests merged in 2021-03, with the labels that each got.

#127 [유병민] Add: initial settings complete
  students/15th/team0/byeongmin-yoo/.gitignore
  students/15th/team0/byeongmin-yoo/manage.py
  students/15th/team0/byeongmin-yoo/requirements.txt
  students/15th/team0/byeongmin-yoo/westagram/__init__.py
  students/15th/team0/byeongmin-yoo/westagram/asgi.py
  students/15th/team0/byeongmin-yoo/westagram/settings.py
  students/15th/team0/byeongmin-yoo/westagram/urls.py
  students/15th/team0/byeongmin-yoo/westagram/wsgi.py
Labels: Status : 리뷰 요청

#191 [손승현] Mission 1: 초기세팅 진행중
  students/17th/team3/seunghyunson_test/manage.py
  students/17th/team3/seunghyunson_test/westagram/__init__.py
  students/17th/team3/seunghyunson_test/westagram/asgi.py
  students/17th/team3/seunghyunson_test/westagram/settings.py
  students/17th/team3/seunghyunson_test/westagram/urls.py
  students/17th/team3/seunghyunson_test/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#193 [안재이] Mission 3: 로그인 엔드포인트 완료
  students/17th/team3/jaeyiahn/.gitignore
  students/17th/team3/jaeyiahn/manage.py
  students/17th/team3/jaeyiahn/requirements.txt
  students/17th/team3/jaeyiahn/user/__init__.py
  students/17th/team3/jaeyiahn/user/admin.py
  students/17th/team3/jaeyiahn/user/apps.py
  students/17th/team3/jaeyiahn/user/migrations/0001_initial.py
  students/17th/team3/jaeyiahn/user/migrations/0002_auto_20210201_1447.py
  students/17th/team3/jaeyiahn/user/migrations/__init__.py
  students/17th/team3/jaeyiahn/user/models.py
  students/17th/team3/jaeyiahn/user/tests.py
  students/17th/team3/jaeyiahn/user/urls.py
  students/17th/team3/jaeyiahn/user/views.py
  students/17th/team3/jaeyiahn/westagram/__init__.py
  students/17th/team3/jaeyiahn/westagram/asgi.py
  students/17th/team3/jaeyiahn/westagram/settings.py
  students/17th/team3/jaeyiahn/westagram/urls.py
  students/17th/team3/jaeyiahn/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항

#194 [송빈호] Mission 10 : 특정 댓글에 대답하는 '대댓글' 달기 완료!
  students/17th/team1/jihunpark/westagram/urls.py
  students/17th/team3/binhosong/1
  students/17th/team3/binhosong/manage.py
  students/17th/team3/binhosong/posting/__init__.py
  students/17th/team3/binhosong/posting/admin.py
  students/17th/team3/binhosong/posting/apps.py
  students/17th/team3/binhosong/posting/migrations/0001_initial.py
  students/17th/team3/binhosong/posting/migrations/0002_auto_20210207_1409.py
  students/17th/team3/binhosong/posting/migrations/0003_auto_20210209_0443.py
  students/17th/team3/binhosong/posting/migrations/0004_like.py
  students/17th/team3/binhosong/posting/migrations/0005_auto_20210209_0541.py
  students/17th/team3/binhosong/posting/migrations/0006_auto_20210209_0542.py
  students/17th/team3/binhosong/posting/migrations/0007_follow.py
  students/17th/team3/binhosong/posting/migrations/0008_auto_20210209_0708.py
  students/17th/team3/binhosong/posting/migrations/0009_comment_level.py
  students/17th/team3/binhosong/posting/migrations/__init__.py
  students/17th/team3/binhosong/posting/models.py
  students/17th/team3/binhosong/posting/tests.py
  students/17th/team3/binhosong/posting/urls.py
  students/17th/team3/binhosong/posting/views.py
  students/17th/team3/binhosong/users/__init__.py
  students/17th/team3/binhosong/users/admin.py
  students/17th/team3/binhosong/users/apps.py
  students/17th/team3/binhosong/users/migrations/0001_initial.py
  students/17th/team3/binhosong/users/migrations/0002_auto_20210201_1027.py
  students/17th/team3/binhosong/users/migrations/0003_auto_20210201_1047.py
  students/17th/team3/binhosong/users/migrations/0004_auto_20210202_0655.py
  students/17th/team3/binhosong/users/migrations/0005_auto_20210204_0759.py
  students/17th/team3/binhosong/users/migrations/__init__.py
  students/17th/team3/binhosong/users/models.py
  students/17th/team3/binhosong/users/tests.py
  students/17th/team3/binhosong/users/urls.py
  students/17th/team3/binhosong/users/views.py
  students/17th/team3/binhosong/users/views.py.bak
  students/17th/team3/binhosong/utils.py
  students/17th/team3/binhosong/westargram/__init__.py
  students/17th/team3/binhosong/westargram/asgi.py
  students/17th/team3/binhosong/westargram/settings.py
  students/17th/team3/binhosong/westargram/urls.py
  students/17th/team3/binhosong/westargram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#195 [최호진] Mission 10: 특정 댓글에 대답하는 '대댓글' 달기 구현
  students/17th/team3/hojinjenechoi/.gitignore
  students/17th/team3/hojinjenechoi/manage.py
  students/17th/team3/hojinjenechoi/post/__init__.py
  students/17th/team3/hojinjenechoi/post/admin.py
  students/17th/team3/hojinjenechoi/post/apps.py
  students/17th/team3/hojinjenechoi/post/migrations/0001_initial.py
  students/17th/team3/hojinjenechoi/post/migrations/0002_comment_parent.py
  students/17th/team3/hojinjenechoi/post/migrations/__init__.py
  students/17th/team3/hojinjenechoi/post/models.py
  students/17th/team3/hojinjenechoi/post/tests.py
  students/17th/team3/hojinjenechoi/post/urls.py
  students/17th/team3/hojinjenechoi/post/views.py
  students/17th/team3/hojinjenechoi/user/__init__.py
  students/17th/team3/hojinjenechoi/user/admin.py
  students/17th/team3/hojinjenechoi/user/apps.py
  students/17th/team3/hojinjenechoi/user/migrations/0001_initial.py
  students/17th/team3/hojinjenechoi/user/migrations/0002_auto_20210201_1950.py
  students/17th/team3/hojinjenechoi/user/migrations/0003_auto_20210201_1955.py
  students/17th/team3/hojinjenechoi/user/migrations/0004_auto_20210202_1528.py
  students/17th/team3/hojinjenechoi/user/migrations/0005_auto_20210202_2353.py
  students/17th/team3/hojinjenechoi/user/migrations/0006_userfollow.py
  students/17th/team3/hojinjenechoi/user/migrations/__init__.py
  students/17th/team3/hojinjenechoi/user/models.py
  students/17th/team3/hojinjenechoi/user/tests.py
  students/17th/team3/hojinjenechoi/user/urls.py
  students/17th/team3/hojinjenechoi/user/utils.py
  students/17th/team3/hojinjenechoi/user/views.py
  students/17th/team3/hojinjenechoi/westagram/__init__.py
  students/17th/team3/hojinjenechoi/westagram/asgi.py
  students/17th/team3/hojinjenechoi/westagram/settings.py
  students/17th/team3/hojinjenechoi/westagram/urls.py
  students/17th/team3/hojinjenechoi/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#196 [이지윤] Mission 3: 로그인 엔드포인트 완료
  students/17th/team1/jiyoonlee/.gitignore
  students/17th/team1/jiyoonlee/manage.py
  students/17th/team1/jiyoonlee/user/__init__.py
  students/17th/team1/jiyoonlee/user/admin.py
  students/17th/team1/jiyoonlee/user/apps.py
  students/17th/team1/jiyoonlee/user/migrations/0001_initial.py
  students/17th/team1/jiyoonlee/user/migrations/0002_user_email.py
  students/17th/team1/jiyoonlee/user/migrations/0003_auto_20210131_1259.py
  students/17th/team1/jiyoonlee/user/migrations/0004_auto_20210201_0803.py
  students/17th/team1/jiyoonlee/user/migrations/0005_auto_20210201_0957.py
  students/17th/team1/jiyoonlee/user/migrations/0006_auto_20210201_1017.py
  students/17th/team1/jiyoonlee/user/migrations/0007_auto_20210201_1151.py
  students/17th/team1/jiyoonlee/user/migrations/__init__.py
  students/17th/team1/jiyoonlee/user/models.py
  students/17th/team1/jiyoonlee/user/tests.py
  students/17th/team1/jiyoonlee/user/urls.py
  students/17th/team1/jiyoonlee/user/views.py
  students/17th/team1/jiyoonlee/westagram/__init__.py
  students/17th/team1/jiyoonlee/westagram/asgi.py
  students/17th/team1/jiyoonlee/westagram/settings.py
  students/17th/team1/jiyoonlee/westagram/urls.py
  students/17th/team1/jiyoonlee/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항

#197 [강승연] Mission 3: 로그인 엔드포인트
  students/17th/team1/seongyeonkang/.gitignore
  students/17th/team1/seongyeonkang/README.md
  students/17th/team1/seongyeonkang/manage.py
  students/17th/team1/seongyeonkang/posting/__init__.py
  students/17th/team1/seongyeonkang/posting/admin.py
  students/17th/team1/seongyeonkang/posting/apps.py
  students/17th/team1/seongyeonkang/posting/migrations/0001_initial.py
  students/17th/team1/seongyeonkang/posting/migrations/__init__.py
  students/17th/team1/seongyeonkang/posting/models.py
  students/17th/team1/seongyeonkang/posting/tests.py
  students/17th/team1/seongyeonkang/posting/urls.py
  students/17th/team1/seongyeonkang/posting/views.py
  students/17th/team1/seongyeonkang/user/__init__.py
  students/17th/team1/seongyeonkang/user/admin.py
  students/17th/team1/seongyeonkang/user/apps.py
  students/17th/team1/seongyeonkang/user/migrations/0001_initial.py
  students/17th/team1/seongyeonkang/user/migrations/__init__.py
  students/17th/team1/seongyeonkang/user/models.py
  students/17th/team1/seongyeonkang/user/tests.py
  students/17th/team1/seongyeonkang/user/urls.py
  students/17th/team1/seongyeonkang/user/views.py
  students/17th/team1/seongyeonkang/utils.py
  students/17th/team1/seongyeonkang/westagram/__init__.py
  students/17th/team1/seongyeonkang/westagram/asgi.py
  students/17th/team1/seongyeonkang/westagram/settings.py
  students/17th/team1/seongyeonkang/westagram/urls.py
  students/17th/team1/seongyeonkang/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항

#198 [박재현] Mission 10 : 특정 댓글에 대답하는 '대댓글' 달기 완료
  students/17th/team1/jaehyeonpark/.gitignore
  students/17th/team1/jaehyeonpark/manage.py
  students/17th/team1/jaehyeonpark/posting/__init__.py
  students/17th/team1/jaehyeonpark/posting/admin.py
  students/17th/team1/jaehyeonpark/posting/apps.py
  students/17th/team1/jaehyeonpark/posting/migrations/0001_initial.py
  students/17th/team1/jaehyeonpark/posting/migrations/0002_auto_20210204_1857.py
  students/17th/team1/jaehyeonpark/posting/migrations/0003_auto_20210204_1900.py
  students/17th/team1/jaehyeonpark/posting/migrations/0004_auto_20210204_1917.py
  students/17th/team1/jaehyeonpark/posting/migrations/0005_follow.py
  students/17th/team1/jaehyeonpark/posting/migrations/0006_auto_20210205_1301.py
  students/17th/team1/jaehyeonpark/posting/migrations/0007_auto_20210205_1302.py
  students/17th/team1/jaehyeonpark/posting/migrations/0008_auto_20210205_1313.py
  students/17th/team1/jaehyeonpark/posting/migrations/0009_auto_20210205_1313.py
  students/17th/team1/jaehyeonpark/posting/migrations/0010_auto_20210205_1510.py
  students/17th/team1/jaehyeonpark/posting/migrations/0011_commentoncomment.py
  students/17th/team1/jaehyeonpark/posting/migrations/0012_commentoncomment_user.py
  students/17th/team1/jaehyeonpark/posting/migrations/0013_auto_20210213_1635.py
  students/17th/team1/jaehyeonpark/posting/migrations/__init__.py
  students/17th/team1/jaehyeonpark/posting/models.py
  students/17th/team1/jaehyeonpark/posting/tests.py
  students/17th/team1/jaehyeonpark/posting/urls.py
  students/17th/team1/jaehyeonpark/posting/views.py
  students/17th/team1/jaehyeonpark/requirements.txt
  students/17th/team1/jaehyeonpark/user/__init__.py
  students/17th/team1/jaehyeonpark/user/admin.py
  students/17th/team1/jaehyeonpark/user/apps.py
  students/17th/team1/jaehyeonpark/user/migrations/0001_initial.py
  students/17th/team1/jaehyeonpark/user/migrations/0002_user_follow.py
  students/17th/team1/jaehyeonpark/user/migrations/__init__.py
  students/17th/team1/jaehyeonpark/user/models.py
  students/17th/team1/jaehyeonpark/user/tests.py
  students/17th/team1/jaehyeonpark/user/urls.py
  students/17th/team1/jaehyeonpark/user/views.py
  students/17th/team1/jaehyeonpark/westagram/__init__.py
  students/17th/team1/jaehyeonpark/westagram/asgi.py
  students/17th/team1/jaehyeonpark/westagram/settings.py
  students/17th/team1/jaehyeonpark/westagram/urls.py
  students/17th/team1/jaehyeonpark/westagram/utils.py
  students/17th/team1/jaehyeonpark/westagram/wsgi.py
Labels: 추가 구현 사항

#199 [강현수] Mission 5: 댓글 등록 진행중
  students/17th/hkk/hyeonsookang/.gitignore
  students/17th/hkk/hyeonsookang/manage.py
  students/17th/hkk/hyeonsookang/posting/__init__.py
  students/17th/hkk/hyeonsookang/posting/admin.py
  students/17th/hkk/hyeonsookang/posting/apps.py
  students/17th/hkk/hyeonsookang/posting/migrations/0001_initial.py
  students/17th/hkk/hyeonsookang/posting/migrations/0002_post_title.py
  students/17th/hkk/hyeonsookang/posting/migrations/0003_comment.py
  students/17th/hkk/hyeonsookang/posting/migrations/0004_remove_comment_user.py
  students/17th/hkk/hyeonsookang/posting/migrations/__init__.py
  students/17th/hkk/hyeonsookang/posting/models.py
  students/17th/hkk/hyeonsookang/posting/tests.py
  students/17th/hkk/hyeonsookang/posting/urls.py
  students/17th/hkk/hyeonsookang/posting/views.py
  students/17th/hkk/hyeonsookang/user/__init__.py
  students/17th/hkk/hyeonsookang/user/admin.py
  students/17th/hkk/hyeonsookang/user/apps.py
  students/17th/hkk/hyeonsookang/user/migrations/0001_initial.py
  students/17th/hkk/hyeonsookang/user/migrations/0002_auto_20210201_1625.py
  students/17th/hkk/hyeonsookang/user/migrations/0003_auto_20210201_2006.py
  students/17th/hkk/hyeonsookang/user/migrations/0004_auto_20210201_2007.py
  students/17th/hkk/hyeonsookang/user/migrations/0005_auto_20210202_1307.py
  students/17th/hkk/hyeonsookang/user/migrations/0006_auto_20210203_1557.py
  students/17th/hkk/hyeonsookang/user/migrations/0007_auto_20210204_1341.py
  students/17th/hkk/hyeonsookang/user/migrations/__init__.py
  students/17th/hkk/hyeonsookang/user/models.py
  students/17th/hkk/hyeonsookang/user/tests.py
  students/17th/hkk/hyeonsookang/user/urls.py
  students/17th/hkk/hyeonsookang/user/views.py
  students/17th/hkk/hyeonsookang/westagram/.gitignore
  students/17th/hkk/hyeonsookang/westagram/__init__.py
  students/17th/hkk/hyeonsookang/westagram/asgi.py
  students/17th/hkk/hyeonsookang/westagram/settings.py
  students/17th/hkk/hyeonsookang/westagram/urls.py
  students/17th/hkk/hyeonsookang/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#200 [김채현] [Mission 10] 특정 댓글에 대답하는 '대댓글' 달기 구현중.....
  students/17th/hkk/chaehyun-kim/.gitignore
  students/17th/hkk/chaehyun-kim/manage.py
  students/17th/hkk/chaehyun-kim/posting/__init__.py
  students/17th/hkk/chaehyun-kim/posting/admin.py
  students/17th/hkk/chaehyun-kim/posting/apps.py
  students/17th/hkk/chaehyun-kim/posting/migrations/0001_initial.py
  students/17th/hkk/chaehyun-kim/posting/migrations/0002_comment.py
  students/17th/hkk/chaehyun-kim/posting/migrations/0003_auto_20210205_0151.py
  students/17th/hkk/chaehyun-kim/posting/migrations/0004_auto_20210207_1719.py
  students/17th/hkk/chaehyun-kim/posting/migrations/0005_auto_20210208_2020.py
  students/17th/hkk/chaehyun-kim/posting/migrations/0006_comment_parent.py
  students/17th/hkk/chaehyun-kim/posting/migrations/__init__.py
  students/17th/hkk/chaehyun-kim/posting/models.py
  students/17th/hkk/chaehyun-kim/posting/tests.py
  students/17th/hkk/chaehyun-kim/posting/urls.py
  students/17th/hkk/chaehyun-kim/posting/utils.py
  students/17th/hkk/chaehyun-kim/posting/views.py
  students/17th/hkk/chaehyun-kim/requirements.txt
  students/17th/hkk/chaehyun-kim/user/__init__.py
  students/17th/hkk/chaehyun-kim/user/admin.py
  students/17th/hkk/chaehyun-kim/user/apps.py
  students/17th/hkk/chaehyun-kim/user/migrations/0001_initial.py
  students/17th/hkk/chaehyun-kim/user/migrations/0002_auto_20210131_1615.py
  students/17th/hkk/chaehyun-kim/user/migrations/0003_auto_20210131_1619.py
  students/17th/hkk/chaehyun-kim/user/migrations/0004_auto_20210201_0717.py
  students/17th/hkk/chaehyun-kim/user/migrations/0005_auto_20210201_0804.py
  students/17th/hkk/chaehyun-kim/user/migrations/0006_auto_20210201_0805.py
  students/17th/hkk/chaehyun-kim/user/migrations/0007_follow.py
  students/17th/hkk/chaehyun-kim/user/migrations/__init__.py
  students/17th/hkk/chaehyun-kim/user/models.py
  students/17th/hkk/chaehyun-kim/user/tests.py
  students/17th/hkk/chaehyun-kim/user/urls.py
  students/17th/hkk/chaehyun-kim/user/views.py
  students/17th/hkk/chaehyun-kim/westagram/__init__.py
  students/17th/hkk/chaehyun-kim/westagram/asgi.py
  students/17th/hkk/chaehyun-kim/westagram/settings.py
  students/17th/hkk/chaehyun-kim/westagram/urls.py
  students/17th/hkk/chaehyun-kim/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#201 [양한아] Mission 10: 특정 댓글에 대답하는 '대댓글' 달기 완료
  students/17th/team1/hanahyang/.gitignore
  students/17th/team1/hanahyang/manage.py
  students/17th/team1/hanahyang/post/__init__.py
  students/17th/team1/hanahyang/post/admin.py
  students/17th/team1/hanahyang/post/apps.py
  students/17th/team1/hanahyang/post/migrations/0001_initial.py
  students/17th/team1/hanahyang/post/migrations/0002_comment.py
  students/17th/team1/hanahyang/post/migrations/0003_auto_20210204_0402.py
  students/17th/team1/hanahyang/post/migrations/0004_auto_20210204_0623.py
  students/17th/team1/hanahyang/post/migrations/0005_comment_parent.py
  students/17th/team1/hanahyang/post/migrations/__init__.py
  students/17th/team1/hanahyang/post/models.py
  students/17th/team1/hanahyang/post/tests.py
  students/17th/team1/hanahyang/post/urls.py
  students/17th/team1/hanahyang/post/views.py
  students/17th/team1/hanahyang/requirements.txt
  students/17th/team1/hanahyang/user/__init__.py
  students/17th/team1/hanahyang/user/admin.py
  students/17th/team1/hanahyang/user/apps.py
  students/17th/team1/hanahyang/user/migrations/0001_initial.py
  students/17th/team1/hanahyang/user/migrations/0002_auto_20210131_0616.py
  students/17th/team1/hanahyang/user/migrations/0003_auto_20210201_0339.py
  students/17th/team1/hanahyang/user/migrations/0004_auto_20210204_0405.py
  students/17th/team1/hanahyang/user/migrations/0005_follow.py
  students/17th/team1/hanahyang/user/migrations/0006_auto_20210204_2045.py
  students/17th/team1/hanahyang/user/migrations/__init__.py
  students/17th/team1/hanahyang/user/models.py
  students/17th/team1/hanahyang/user/tests.py
  students/17th/team1/hanahyang/user/urls.py
  students/17th/team1/hanahyang/user/utils.py
  students/17th/team1/hanahyang/user/views.py
  students/17th/team1/hanahyang/westagram/__init__.py
  students/17th/team1/hanahyang/westagram/asgi.py
  students/17th/team1/hanahyang/westagram/settings.py
  students/17th/team1/hanahyang/westagram/urls.py
  students/17th/team1/hanahyang/westagram/wsgi.py
Labels: 추가 구현 사항

#202 [정희영] Mission 10: 특정 댓글에 대답하는 '대댓글' 달기 완료
  students/17th/team-one/heeyoungjeong/.gitignore
  students/17th/team-one/heeyoungjeong/manage.py
  students/17th/team-one/heeyoungjeong/posting/__init__.py
  students/17th/team-one/heeyoungjeong/posting/admin.py
  students/17th/team-one/heeyoungjeong/posting/apps.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0001_initial.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0002_auto_20210207_1125.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0003_auto_20210207_1222.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0004_auto_20210207_2215.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0005_comment.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0006_auto_20210208_2113.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0007_auto_20210208_2118.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0008_auto_20210208_2119.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0009_auto_20210208_2120.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0010_auto_20210208_2142.py
  students/17th/team-one/heeyoungjeong/posting/migrations/0011_auto_20210210_1653.py
  students/17th/team-one/heeyoungjeong/posting/migrations/__init__.py
  students/17th/team-one/heeyoungjeong/posting/models.py
  students/17th/team-one/heeyoungjeong/posting/tests.py
  students/17th/team-one/heeyoungjeong/posting/urls.py
  students/17th/team-one/heeyoungjeong/posting/views.py
  students/17th/team-one/heeyoungjeong/requirements.txt
  students/17th/team-one/heeyoungjeong/user/__init__.py
  students/17th/team-one/heeyoungjeong/user/admin.py
  students/17th/team-one/heeyoungjeong/user/apps.py
  students/17th/team-one/heeyoungjeong/user/migrations/0001_initial.py
  students/17th/team-one/heeyoungjeong/user/migrations/0002_auto_20210201_0414.py
  students/17th/team-one/heeyoungjeong/user/migrations/0003_auto_20210201_1317.py
  students/17th/team-one/heeyoungjeong/user/migrations/0004_auto_20210201_1324.py
  students/17th/team-one/heeyoungjeong/user/migrations/0005_auto_20210204_0409.py
  students/17th/team-one/heeyoungjeong/user/migrations/0006_auto_20210209_1720.py
  students/17th/team-one/heeyoungjeong/user/migrations/__init__.py
  students/17th/team-one/heeyoungjeong/user/models.py
  students/17th/team-one/heeyoungjeong/user/tests.py
  students/17th/team-one/heeyoungjeong/user/urls.py
  students/17th/team-one/heeyoungjeong/user/views.py
  students/17th/team-one/heeyoungjeong/utils.py
  students/17th/team-one/heeyoungjeong/westagram/__init__.py
  students/17th/team-one/heeyoungjeong/westagram/asgi.py
  students/17th/team-one/heeyoungjeong/westagram/settings.py
  students/17th/team-one/heeyoungjeong/westagram/urls.py
  students/17th/team-one/heeyoungjeong/westagram/wsgi.py
Labels: 추가 구현 사항

#203 [조수아] Mission 10: 특정 댓글에 대답하는 '대댓글' 달기 완료
  students/17th/team1/suacho/.gitignore
  students/17th/team1/suacho/manage.py
  students/17th/team1/suacho/posting/__init__.py
  students/17th/team1/suacho/posting/admin.py
  students/17th/team1/suacho/posting/apps.py
  students/17th/team1/suacho/posting/migrations/0001_initial.py
  students/17th/team1/suacho/posting/migrations/0002_posting_writer.py
  students/17th/team1/suacho/posting/migrations/0003_comment.py
  students/17th/team1/suacho/posting/migrations/0004_like.py
  students/17th/team1/suacho/posting/migrations/0005_auto_20210205_1605.py
  students/17th/team1/suacho/posting/migrations/0006_remove_like_username.py
  students/17th/team1/suacho/posting/migrations/0007_like_created_at.py
  students/17th/team1/suacho/posting/migrations/0008_remove_comment_writer.py
  students/17th/team1/suacho/posting/migrations/0009_remove_posting_writer.py
  students/17th/team1/suacho/posting/migrations/0010_auto_20210211_1613.py
  students/17th/team1/suacho/posting/migrations/0011_posting_updated_at.py
  students/17th/team1/suacho/posting/migrations/0012_comment_parent_comment.py
  students/17th/team1/suacho/posting/migrations/__init__.py
  students/17th/team1/suacho/posting/models.py
  students/17th/team1/suacho/posting/tests.py
  students/17th/team1/suacho/posting/urls.py
  students/17th/team1/suacho/posting/views.py
  students/17th/team1/suacho/user/__init__.py
  students/17th/team1/suacho/user/admin.py
  students/17th/team1/suacho/user/apps.py
  students/17th/team1/suacho/user/migrations/0001_initial.py
  students/17th/team1/suacho/user/migrations/0002_auto_20210201_0326.py
  students/17th/team1/suacho/user/migrations/0003_auto_20210201_0420.py
  students/17th/team1/suacho/user/migrations/0004_follow.py
  students/17th/team1/suacho/user/migrations/__init__.py
  students/17th/team1/suacho/user/models.py
  students/17th/team1/suacho/user/tests.py
  students/17th/team1/suacho/user/urls.py
  students/17th/team1/suacho/user/utils.py
  students/17th/team1/suacho/user/views.py
  students/17th/team1/suacho/westagram/__init__.py
  students/17th/team1/suacho/westagram/asgi.py
  students/17th/team1/suacho/westagram/settings.py
  students/17th/team1/suacho/westagram/urls.py
  students/17th/team1/suacho/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#205 [이동근] Mission8 : 게시물, 댓글 제거 구현 완료
  students/17th/team1/donggeunLEE/.gitignore
  students/17th/team1/donggeunLEE/:w
  students/17th/team1/donggeunLEE/Posting/__init__.py
  students/17th/team1/donggeunLEE/Posting/admin.py
  students/17th/team1/donggeunLEE/Posting/apps.py
  students/17th/team1/donggeunLEE/Posting/migrations/0001_initial.py
  students/17th/team1/donggeunLEE/Posting/migrations/0002_usercomment.py
  students/17th/team1/donggeunLEE/Posting/migrations/0003_auto_20210207_0954.py
  students/17th/team1/donggeunLEE/Posting/migrations/0004_auto_20210207_1058.py
  students/17th/team1/donggeunLEE/Posting/migrations/0005_additonalcomment.py
  students/17th/team1/donggeunLEE/Posting/migrations/__init__.py
  students/17th/team1/donggeunLEE/Posting/models.py
  students/17th/team1/donggeunLEE/Posting/tests.py
  students/17th/team1/donggeunLEE/Posting/urls.py
  students/17th/team1/donggeunLEE/Posting/views.py
  students/17th/team1/donggeunLEE/User/__init__.py
  students/17th/team1/donggeunLEE/User/admin.py
  students/17th/team1/donggeunLEE/User/apps.py
  students/17th/team1/donggeunLEE/User/migrations/0001_initial.py
  students/17th/team1/donggeunLEE/User/migrations/0002_auto_20210202_0644.py
  students/17th/team1/donggeunLEE/User/migrations/0003_auto_20210202_0953.py
  students/17th/team1/donggeunLEE/User/migrations/0004_follow.py
  students/17th/team1/donggeunLEE/User/migrations/__init__.py
  students/17th/team1/donggeunLEE/User/models.py
  students/17th/team1/donggeunLEE/User/tests.py
  students/17th/team1/donggeunLEE/User/urls.py
  students/17th/team1/donggeunLEE/User/utilities.py
  students/17th/team1/donggeunLEE/User/views.py
  students/17th/team1/donggeunLEE/\
  students/17th/team1/donggeunLEE/manage.py
  students/17th/team1/donggeunLEE/user
  students/17th/team1/donggeunLEE/westagram/.gitignore
  students/17th/team1/donggeunLEE/westagram/__init__.py
  students/17th/team1/donggeunLEE/westagram/asgi.py
  students/17th/team1/donggeunLEE/westagram/requirements.txt
  students/17th/team1/donggeunLEE/westagram/settings.py
  students/17th/team1/donggeunLEE/westagram/urls.py
  students/17th/team1/donggeunLEE/westagram/utilities.py
  students/17th/team1/donggeunLEE/westagram/wsgi.py
Labels: Status : 리뷰 요청, 추가 구현 사항

#206 [김하성] [Mission 10] 특정 댓글에 대답하는 '대댓글' 달기 완료
  students/17th/team1/markkim/manage.py
  students/17th/team1/markkim/posts/__init__.py
  students/17th/team1/markkim/posts/admin.py
  students/17th/team1/markkim/posts/apps.py
  students/17th/team1/markkim/posts/migrations/0001_initial.py
  students/17th/team1/markkim/posts/migrations/0002_auto_20210207_0152.py
  students/17th/team1/markkim/posts/migrations/0003_auto_20210207_0155.py
  students/17th/team1/markkim/posts/migrations/0004_comment.py
  students/17th/team1/markkim/posts/migrations/0005_like.py
  students/17th/team1/markkim/posts/migrations/0006_auto_20210208_1618.py
  students/17th/team1/markkim/posts/migrations/0007_commentreply.py
  students/17th/team1/markkim/posts/migrations/0008_auto_20210211_1719.py
  students/17th/team1/markkim/posts/migrations/__init__.py
  students/17th/team1/markkim/posts/models.py
  students/17th/team1/markkim/posts/tests.py
  students/17th/team1/markkim/posts/urls.py
  students/17th/team1/markkim/posts/views.py
  students/17th/team1/markkim/user/__init__.py
  students/17th/team1/markkim/user/admin.py
  students/17th/team1/markkim/user/apps.py
  students/17th/team1/markkim/user/migrations/0001_initial.py
  students/17th/team1/markkim/user/migrations/0002_auto_20210202_1134.py
  students/17th/team1/markkim/user/migrations/0003_follower.py
  students/17th/team1/markkim/user/migrations/0004_auto_20210210_2200.py
  students/17th/team1/markkim/user/migrations/__init__.py
  students/17th/team1/markkim/user/models.py
  students/17th/team1/markkim/user/tests.py
  students/17th/team1/markkim/user/urls.py
  students/17th/team1/markkim/user/utils.py
  students/17th/team1/markkim/user/views.py
  students/17th/team1/markkim/westagram/.gitignore
  students/17th/team1/markkim/westagram/__init__.py
  students/17th/team1/markkim/westagram/asgi.py
  students/17th/team1/markkim/westagram/requirements.txt
  students/17th/team1/markkim/westagram/settings.py
  students/17th/team1/markkim/westagram/urls.py
  students/17th/team1/markkim/westagram/wsgi.py
Labels: 추가 구현 사항

#207 [조혜윤] Mission 3 : 로그인 엔드포인트
  students/17th/raon/hyeyoon/manage.py
  students/17th/raon/hyeyoon/posting/__init__.py
  students/17th/raon/hyeyoon/posting/admin.py
  students/17th/raon/hyeyoon/posting/apps.py
  students/17th/raon/hyeyoon/posting/migrations/0001_initial.py
  students/17th/raon/hyeyoon/posting/migrations/0002_posting_discription.py
  students/17th/raon/hyeyoon/posting/migrations/0003_auto_20210210_0715.py
  students/17th/raon/hyeyoon/posting/migrations/0004_comment.py
  students/17th/raon/hyeyoon/posting/migrations/0005_auto_20210210_0905.py
  students/17th/raon/hyeyoon/posting/migrations/__init__.py
  students/17th/raon/hyeyoon/posting/models.py
  students/17th/raon/hyeyoon/posting/tests.py
  students/17th/raon/hyeyoon/posting/urls.py
  students/17th/raon/hyeyoon/posting/views.py
  students/17th/raon/hyeyoon/user/__init__.py
  students/17th/raon/hyeyoon/user/admin.py
  students/17th/raon/hyeyoon/user/apps.py
  students/17th/raon/hyeyoon/user/migrations/0001_initial.py
  students/17th/raon/hyeyoon/user/migrations/__init__.py
  students/17th/raon/hyeyoon/user/models.py
  students/17th/raon/hyeyoon/user/tests.py
  students/17th/raon/hyeyoon/user/urls.py
  students/17th/raon/hyeyoon/user/views.py
  students/17th/raon/hyeyoon/westagram/__init__.py
  students/17th/raon/hyeyoon/westagram/asgi.py
  students/17th/raon/hyeyoon/westagram/settings.py
  students/17th/raon/hyeyoon/westagram/urls.py
  students/17th/raon/hyeyoon/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항

#208 [남채린] Mission 5 : 게시물에 댓글 등록
  students/17th/raon/chaerin/manage.py
  students/17th/raon/chaerin/posting/__init__.py
  students/17th/raon/chaerin/posting/admin.py
  students/17th/raon/chaerin/posting/apps.py
  students/17th/raon/chaerin/posting/migrations/0001_initial.py
  students/17th/raon/chaerin/posting/migrations/0002_auto_20210209_0218.py
  students/17th/raon/chaerin/posting/migrations/0003_auto_20210209_0224.py
  students/17th/raon/chaerin/posting/migrations/0004_post_user.py
  students/17th/raon/chaerin/posting/migrations/0005_post_created_at.py
  students/17th/raon/chaerin/posting/migrations/0006_comment.py
  students/17th/raon/chaerin/posting/migrations/0007_auto_20210211_1540.py
  students/17th/raon/chaerin/posting/migrations/__init__.py
  students/17th/raon/chaerin/posting/models.py
  students/17th/raon/chaerin/posting/tests.py
  students/17th/raon/chaerin/posting/urls.py
  students/17th/raon/chaerin/posting/views.py
  students/17th/raon/chaerin/user/__init__.py
  students/17th/raon/chaerin/user/admin.py
  students/17th/raon/chaerin/user/apps.py
  students/17th/raon/chaerin/user/migrations/0001_initial.py
  students/17th/raon/chaerin/user/migrations/0002_auto_20210202_0909.py
  students/17th/raon/chaerin/user/migrations/0003_auto_20210202_1057.py
  students/17th/raon/chaerin/user/migrations/0004_auto_20210203_0610.py
  students/17th/raon/chaerin/user/migrations/0005_auto_20210203_0614.py
  students/17th/raon/chaerin/user/migrations/0006_auto_20210203_1523.py
  students/17th/raon/chaerin/user/migrations/__init__.py
  students/17th/raon/chaerin/user/models.py
  students/17th/raon/chaerin/user/tests.py
  students/17th/raon/chaerin/user/urls.py
  students/17th/raon/chaerin/user/utils.py
  students/17th/raon/chaerin/user/views.py
  students/17th/raon/chaerin/westagram/__init__.py
  students/17th/raon/chaerin/westagram/asgi.py
  students/17th/raon/chaerin/westagram/settings.py
  students/17th/raon/chaerin/westagram/urls.py
  students/17th/raon/chaerin/westagram/wsgi.py
Labels: 추가 구현 사항

#209 [심규보] Mission 3 : 로그인 엔드포인트 완료
  students/17th/team1/gyuboshim/westagram/.gitignore
  students/17th/team1/gyuboshim/westagram/manage.py
  students/17th/team1/gyuboshim/westagram/post/__init__.py
  students/17th/team1/gyuboshim/westagram/post/admin.py
  students/17th/team1/gyuboshim/westagram/post/apps.py
  students/17th/team1/gyuboshim/westagram/post/migrations/0001_initial.py
  students/17th/team1/gyuboshim/westagram/post/migrations/__init__.py
  students/17th/team1/gyuboshim/westagram/post/models.py
  students/17th/team1/gyuboshim/westagram/post/tests.py
  students/17th/team1/gyuboshim/westagram/post/urls.py
  students/17th/team1/gyuboshim/westagram/post/views.py
  students/17th/team1/gyuboshim/westagram/requirements.txt
  students/17th/team1/gyuboshim/westagram/user/__init__.py
  students/17th/team1/gyuboshim/westagram/user/admin.py
  students/17th/team1/gyuboshim/westagram/user/apps.py
  students/17th/team1/gyuboshim/westagram/user/migrations/0001_initial.py
  students/17th/team1/gyuboshim/westagram/user/migrations/0002_auto_20210202_1124.py
  students/17th/team1/gyuboshim/westagram/user/migrations/0003_auto_20210203_0332.py
  students/17th/team1/gyuboshim/westagram/user/migrations/0004_auto_20210203_0506.py
  students/17th/team1/gyuboshim/westagram/user/migrations/__init__.py
  students/17th/team1/gyuboshim/westagram/user/models.py
  students/17th/team1/gyuboshim/westagram/user/tests.py
  students/17th/team1/gyuboshim/westagram/user/urls.py
  students/17th/team1/gyuboshim/westagram/user/views.py
  students/17th/team1/gyuboshim/westagram/westagram/__init__.py
  students/17th/team1/gyuboshim/westagram/westagram/asgi.py
  students/17th/team1/gyuboshim/westagram/westagram/settings.py
  students/17th/team1/gyuboshim/westagram/westagram/urls.py
  students/17th/team1/gyuboshim/westagram/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항

#210 [허정윤] Mission 3 로그인 엔드포인트 완료
  students/17th/hkk/jeongyun-heo/.gitignore
  students/17th/hkk/jeongyun-heo/manage.py
  students/17th/hkk/jeongyun-heo/posting/__init__.py
  students/17th/hkk/jeongyun-heo/posting/admin.py
  students/17th/hkk/jeongyun-heo/posting/apps.py
  students/17th/hkk/jeongyun-heo/posting/migrations/0001_initial.py
  students/17th/hkk/jeongyun-heo/posting/migrations/__init__.py
  students/17th/hkk/jeongyun-heo/posting/models.py
  students/17th/hkk/jeongyun-heo/posting/tests.py
  students/17th/hkk/jeongyun-heo/posting/urls.py
  students/17th/hkk/jeongyun-heo/posting/views.py
  students/17th/hkk/jeongyun-heo/requirements.txt
  students/17th/hkk/jeongyun-heo/user/__init__.py
  students/17th/hkk/jeongyun-heo/user/admin.py
  students/17th/hkk/jeongyun-heo/user/apps.py
  students/17th/hkk/jeongyun-heo/user/migrations/0001_initial.py
  students/17th/hkk/jeongyun-heo/user/migrations/0002_auto_20210208_2243.py
  students/17th/hkk/jeongyun-heo/user/migrations/__init__.py
  students/17th/hkk/jeongyun-heo/user/models.py
  students/17th/hkk/jeongyun-heo/user/tests.py
  students/17th/hkk/jeongyun-heo/user/urls.py
  students/17th/hkk/jeongyun-heo/user/views.py
  students/17th/hkk/jeongyun-heo/westagram/__init__.py
  students/17th/hkk/jeongyun-heo/westagram/asgi.py
  students/17th/hkk/jeongyun-heo/westagram/settings.py
  students/17th/hkk/jeongyun-heo/westagram/urls.py
  students/17th/hkk/jeongyun-heo/westagram/wsgi.py
Labels: Status : Accepted, 필수 구현 사항

#211 [김치오] Mission 3 : 로그인 엔드포인트 완료
  students/17th/team1/ChiohKim/.gitignore
  students/17th/team1/ChiohKim/manage.py
  students/17th/team1/ChiohKim/user/__init__.py
  students/17th/team1/ChiohKim/user/admin.py
  students/17th/team1/ChiohKim/user/apps.py
  students/17th/team1/ChiohKim/user/migrations/0001_initial.py
  students/17th/team1/ChiohKim/user/migrations/0002_auto_20210204_0243.py
  students/17th/team1/ChiohKim/user/migrations/__init__.py
  students/17th/team1/ChiohKim/user/models.py
  students/17th/team1/ChiohKim/user/tests.py
  students/17th/team1/ChiohKim/user/urls.py
  students/17th/team1/ChiohKim/user/views.py
  students/17th/team1/ChiohKim/westagram/__init__.py
  students/17th/team1/ChiohKim/westagram/asgi.py
  students/17th/team1/ChiohKim/westagram/settings.py
  students/17th/team1/ChiohKim/westagram/urls.py
  students/17th/team1/ChiohKim/westagram/wsgi.py
Labels: Status : Accepted

#212 [이준하] Mission 2 : 회원가입 엔드포인트
  students/17th/team4/leejunha/.gitignore
  students/17th/team4/leejunha/manage.py
  students/17th/team4/leejunha/requirements.txt
  students/17th/team4/leejunha/user/__init__.py
  students/17th/team4/leejunha/user/admin.py
  students/17th/team4/leejunha/user/apps.py
  students/17th/team4/leejunha/user/migrations/0001_initial.py
  students/17th/team4/leejunha/user/migrations/0002_auto_20210209_0840.py
  students/17th/team4/leejunha/user/migrations/0003_auto_20210209_0842.py
  students/17th/team4/leejunha/user/migrations/__init__.py
  students/17th/team4/leejunha/user/models.py
  students/17th/team4/leejunha/user/tests.py
  students/17th/team4/leejunha/user/urls.py
  students/17th/team4/leejunha/user/views.py
  students/17th/team4/leejunha/westagram/__init__.py
  students/17th/team4/leejunha/westagram/asgi.py
  students/17th/team4/leejunha/westagram/settings.py
  students/17th/team4/leejunha/westagram/urls.py
  students/17th/team4/leejunha/westagram/wsgi.py
Labels: Status : 수정 요청, 필수 구현 사항

#223 [손승현] Mission 1: 초기세팅 완료
  students/18th/team2/eunwoosong/manage.py
  students/18th/team2/eunwoosong/westagram/__init__.py
  students/18th/team2/eunwoosong/westagram/asgi.py
  students/18th/team2/eunwoosong/westagram/settings.py
  students/18th/team2/eunwoosong/westagram/urls.py
  students/18th/team2/eunwoosong/westagram/wsgi.py
Labels: Status : 리뷰 요청, 필수 구현 사항
